"use strict";

let CATEGORY_TREE={"UI":["登入","角色建立","角色選擇","系統","NPC對話","商城","背包","技能欄","按鈕","其他"],"Item":["武器","防具","飾品","卷軸","消耗品","材料","任務","其他"],"Character":["玩家","NPC","怪物","Boss","寵物","其他"],"Effect":["技能","Buff","Debuff","火焰","雷電","冰","其他"],"Map":["其他"],"Unknown":[]};
let CATEGORIES=categoryTreeValues();
const PAGE_SIZE=60, DB_NAME="LineageAssetStudio", STORE="handles";
const SOURCE_ORDER={IMG:0,TBT:1,PNG:2},LANG_ORDER={KR:0,TW:1,CN:2,JP:3,EN:4};
const MEDIA_EXTS=new Set(["png","jpg","jpeg","ogg","wav","mp3","mp4"]);
const state={root:null,assets:[],groups:[],filtered:[],visibleAssets:[],viewMode:"serial",appMode:"normal",catalogUnknownOnly:true,sessionClassified:0,selected:new Set(),page:1,urls:[],saveTimer:null,savePromise:Promise.resolve(),scanWarnings:[],lastScanAt:null,anchorKey:null,currentCategory:"Unknown",undo:[],redo:[],drag:null,mediaFiles:[],mediaSelected:new Set(),importFiles:[],folderStack:[],categoryEditor:null,classificationsSinceBackup:0,projectDirty:false,dirtySince:null,lastBackupAt:null,backupCount:0,backupBusy:false};
const $=id=>document.getElementById(id);

document.addEventListener("DOMContentLoaded",init);
async function init(){
  fillSelect($("categoryFilter"),CATEGORIES); fillSelect($("batchCategory"),CATEGORIES,false);
  buildCategoryTree();
  bindEvents();
  setInterval(checkTimedBackup,60000);
  if(!window.showDirectoryPicker){showNotice("此瀏覽器不支援 File System Access API，請使用最新版 Chrome 或 Edge。",true);$("chooseFolder").disabled=true;return;}
  try{const handle=await dbGet("root");if(handle&&await verifyPermission(handle,false)){await openRoot(handle)}}catch(e){console.warn(e)}
}

function bindEvents(){
  $("chooseFolder").onclick=chooseFolder; $("rescan").onclick=()=>scanRoot(true);
  ["search","sourceFilter","spriteFilter","langFilter","categoryFilter","minWidth","maxWidth","minHeight","maxHeight"].forEach(id=>$(id).addEventListener(id==="search"||id.startsWith("min")||id.startsWith("max")?"input":"change",applyFilters));
  $("clearFilters").onclick=clearFilters; $("firstPage").onclick=()=>setPage(1); $("prevPage").onclick=()=>setPage(state.page-1); $("nextPage").onclick=()=>setPage(state.page+1); $("lastPage").onclick=()=>setPage(pageCount()); $("goPage").onclick=jumpToPage; $("pageInput").onkeydown=e=>{if(e.key==="Enter")jumpToPage()};
  $("selectPage").onchange=togglePageSelection; $("clearSelection").onclick=()=>{state.selected.clear();render();updateSelection()};
  $("applyCategory").onclick=applyCategory; $("addTags").onclick=addTags;
  $("batchCategory").onchange=()=>{state.currentCategory=$("batchCategory").value;updateSelection()};
  $("exportJson").onclick=()=>downloadJSON("assets_index.json",publicAssets()); $("exportCsv").onclick=exportCSV;
  $("exportProject").onclick=()=>downloadJSON("lineage_asset_project.json",projectPayload()); $("importProject").onchange=importProject;
  $("closeDialog").onclick=()=>closeDialog(); $("groupDialog").addEventListener("click",e=>{if(e.target===$("groupDialog"))closeDialog()});
  $("scanReport").onclick=openReport; $("closeReport").onclick=()=>$("reportDialog").close(); $("reportSearch").oninput=renderReport; $("copyReport").onclick=copyReport; $("downloadReport").onclick=downloadReport;
  $("gallery").addEventListener("mousedown",startBandSelection); $("gallery").addEventListener("contextmenu",openContextMenu);
  document.addEventListener("keydown",handleKeyboard); document.addEventListener("click",e=>{if(!$("contextMenu").contains(e.target))hideContextMenu()});
  $("contextMenu").addEventListener("click",handleContextAction); $("confirmTags").onclick=confirmDialogTags;
  document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).close());
  $("sourceView").onclick=()=>setViewMode("source"); $("serialView").onclick=()=>setViewMode("serial");
  $("quickSource").onchange=()=>{$("sourceFilter").value=$("quickSource").value;applyFilters()};
  $("quickSprite").onchange=()=>jumpToSprite($("quickSprite").value);
  $("exportMedia").onclick=openMediaExport; $("importMedia").onclick=chooseMediaImport; $("mediaSearch").oninput=renderMediaFiles;
  $("selectAllMedia").onclick=selectAllMedia; $("clearMediaSelection").onclick=()=>{state.mediaSelected.clear();renderMediaFiles()}; $("confirmMediaExport").onclick=exportSelectedMedia;
  $("folderUp").onclick=folderUp; $("createFolder").onclick=createImportFolder; $("confirmMediaImport").onclick=importToCurrentFolder;
  $("normalMode").onclick=()=>setAppMode("normal"); $("catalogMode").onclick=()=>setAppMode("catalog");
  $("selectRange").onclick=selectSerialRange; $("serialRange").onkeydown=e=>{if(e.key==="Enter")selectSerialRange()};
  $("previousUnknown").onclick=()=>jumpUnknown(-1); $("nextUnknown").onclick=()=>jumpUnknown(1); $("toggleUnknown").onclick=toggleCatalogUnknown;
  $("addRootCategory").onclick=()=>openCategoryEditor({mode:"add-root"}); $("saveCategoryEditor").onclick=saveCategoryEditor; $("categoryName").onkeydown=e=>{if(e.key==="Enter")saveCategoryEditor()};
  $("createBackup").onclick=()=>createSnapshot("manual"); $("viewBackups").onclick=openBackupDialog;
}

async function chooseFolder(){
  try{const handle=await showDirectoryPicker({mode:"readwrite",id:"lineage-assets"});if(!await verifyPermission(handle,true))throw Error("需要資料夾讀寫權限，才能儲存專案索引。");await dbPut("root",handle);await openRoot(handle)}catch(e){if(e.name!=="AbortError")showNotice(e.message,true)}
}
async function verifyPermission(h,ask){const opts={mode:"readwrite"};if(await h.queryPermission(opts)==="granted")return true;return ask&&(await h.requestPermission(opts)==="granted")}
async function openRoot(handle){
  state.root=handle;$("folderStatus").textContent=`已開啟：${handle.name}`;$("rescan").disabled=false;
  try{const studio=await handle.getDirectoryHandle(".LineageAssetStudio");const idx=await readJSON(studio,"assets_index.json");state.assets=normalizeAssets(idx);try{const p=await readJSON(studio,"project.json");applyProject(p);state.classificationsSinceBackup=Number(p.backupState?.classificationsSinceBackup)||0;state.lastBackupAt=p.backupState?.lastBackupAt?new Date(p.backupState.lastBackupAt):null}catch{}try{const s=await readJSON(studio,"settings.json");state.scanWarnings=Array.isArray(s.scanWarnings)?s.scanWarnings:[];state.lastScanAt=s.lastScan?new Date(s.lastScan):null;if(validCategoryTree(s.categoryTree)){CATEGORY_TREE=s.categoryTree;CATEGORIES=categoryTreeValues();buildCategoryTree();refreshCategoryControls()}$("scanReport").disabled=!state.lastScanAt}catch{}await initializeBackupSystem();showNotice(`已載入現有索引，共 ${state.assets.length.toLocaleString()} 張圖片。`);afterLoad()}catch(e){if(e.name==="NotFoundError")await scanRoot(true);else showNotice(`索引讀取失敗：${e.message}`,true)}
}

async function scanRoot(){
  if(!state.root)return;
  const previous=Object.fromEntries(state.assets.map(a=>[a.uid,{category:a.category,categoryLabel:a.categoryLabel,categoryPath:a.categoryPath,tags:a.tags}]));
  setBusy(true,"正在尋找 PNG…",0);state.assets=[];state.selected.clear();
  try{
    const found=[],warnings=[];state.scanWarnings=warnings;state.lastScanAt=new Date();
    await walk(state.root,"",found,warnings);
    if(!found.length)throw Error("在 01.IMG、02.TBT、03.PNG 結構中找不到可讀取的 PNG");
    let done=0,skipped=0;
    for(const item of found){
      const parsed=parsePath(item.path);
      if(!parsed){skipped++;warnings.push(`${item.path}：路徑或檔名不符合索引規則`);continue}
      try{
        const file=await item.handle.getFile(),size=await imageSize(file),old=previous[parsed.uid];
        const inferred=parsed.assetPrefix==="ms"?"Character > 怪物":parsed.assetPrefix==="ge"?"Effect > 其他":"Unknown";
        const label=old?.categoryLabel||old?.category||inferred,path=old?.categoryPath||categoryPathFromLabel(label);
        state.assets.push({...parsed,fileName:file.name,relativePath:item.path,width:size.width,height:size.height,category:label,categoryLabel:label,categoryPath:path,tags:old?.tags||[]});
      }catch(e){skipped++;warnings.push(`${item.path}：${e.message}`)}
      done++;
      if(done%20===0||done===found.length){setBusy(true,`正在建立索引 ${done.toLocaleString()} / ${found.length.toLocaleString()}（略過 ${skipped.toLocaleString()}）`,found.length?done/found.length:1);await nextFrame()}
    }
    if(!state.assets.length)throw Error("找到 PNG，但路徑或檔名不符合預期格式（例如 77c.png 或 ms1039.png）");
    state.assets.sort((a,b)=>a.sourceType.localeCompare(b.sourceType)||a.spriteName.localeCompare(b.spriteName,undefined,{numeric:true})||a.originalNumber-b.originalNumber||a.lang.localeCompare(b.lang));
    await createStudioFiles();await initializeBackupSystem();afterLoad();
    const suffix=skipped||warnings.length?`，略過 ${skipped.toLocaleString()} 個不符合命名規則或無法讀取的檔案／資料夾。`:"。";
    showNotice(`掃描完成，共建立 ${state.assets.length.toLocaleString()} 張圖片的索引${suffix}`,warnings.length>0);
    $("scanReport").disabled=false;
    if(warnings.length)console.warn("Lineage Asset Studio 掃描警告：",warnings);
  }catch(e){
    const detail=e?.message||String(e);
    showNotice(`掃描失敗：${detail}。請確認選擇的是 LineageAssets 根目錄，且瀏覽器已取得讀寫權限。`,true);
    console.error("Lineage Asset Studio 掃描失敗",e);
  }finally{setBusy(false)}
}
async function walk(dir,prefix,out,warnings){
  try{
    for await(const [name,h] of dir.entries()){
      if(name===".LineageAssetStudio")continue;
      const p=prefix?`${prefix}/${name}`:name;
      if(h.kind==="directory")await walk(h,p,out,warnings);
      else if(name.toLowerCase().endsWith(".png"))out.push({path:p,handle:h});
    }
  }catch(e){if(!prefix)throw e;warnings.push(`${prefix}：${e.message}`)}
}
function parsePath(path){const parts=path.split("/");if(parts.length<3)return null;const types={"01.IMG":"IMG","02.TBT":"TBT","03.PNG":"PNG"};const sourceType=types[parts[0]];if(!sourceType)return null;const file=parts.at(-1),m=file.match(/^(cs|ms|ge)?(\d+)([chej])?\.png$/i);if(!m)return null;const spriteName=parts.at(-2),assetPrefix=(m[1]||"").toLowerCase(),originalNumber=Number(m[2]),suffix=(m[3]||"").toLowerCase(),langs={c:"TW",h:"CN",j:"JP",e:"EN"},lang=langs[suffix]||"KR",prefixUid=assetPrefix?`_${assetPrefix.toUpperCase()}`:"";return{uid:`${sourceType}_${spriteName}${prefixUid}_${originalNumber}_${lang}`,sourceType,spriteName,assetPrefix,originalNumber,lang}}
async function imageSize(file){try{const b=await createImageBitmap(file);const s={width:b.width,height:b.height};b.close();return s}catch{return await new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{resolve({width:im.naturalWidth,height:im.naturalHeight});URL.revokeObjectURL(u)};im.onerror=()=>{URL.revokeObjectURL(u);reject(Error(`無法讀取圖片：${file.name}`))};im.src=u})}}

function settingsPayload(){return{version:2,groupByOriginalNumber:true,pageSize:PAGE_SIZE,lastScan:(state.lastScanAt||new Date()).toISOString(),scanWarnings:state.scanWarnings,categoryTree:CATEGORY_TREE}}
async function createStudioFiles(){const d=await state.root.getDirectoryHandle(".LineageAssetStudio",{create:true});await d.getDirectoryHandle("thumbnails",{create:true});await d.getDirectoryHandle("cache",{create:true});await d.getDirectoryHandle("backups",{create:true});await writeJSON(d,"assets_index.json",indexAssets());await writeJSON(d,"project.json",projectPayload());await writeJSON(d,"settings.json",settingsPayload())}
async function writeJSON(dir,name,data){const h=await dir.getFileHandle(name,{create:true}),w=await h.createWritable();await w.write(JSON.stringify(data,null,2));await w.close()}
async function readJSON(dir,name){const h=await dir.getFileHandle(name),f=await h.getFile();return JSON.parse(await f.text())}
function publicAssets(){return state.assets.map(({uid,sourceType,spriteName,assetPrefix,originalNumber,lang,fileName,relativePath,width,height,category,categoryPath,categoryLabel,tags})=>({uid,sourceType,spriteName,assetPrefix:assetPrefix||"",originalNumber,lang,fileName,relativePath,width,height,category,categoryPath,categoryLabel,tags}))}
function indexAssets(){return publicAssets().map(a=>({...a,category:"Unknown",categoryPath:["Unknown"],categoryLabel:"Unknown",tags:[]}))}
function projectPayload(){return{app:"Lineage Asset Studio",version:3,savedAt:new Date().toISOString(),categoryTree:CATEGORY_TREE,settings:settingsPayload(),backupState:{classificationsSinceBackup:state.classificationsSinceBackup,lastBackupAt:state.lastBackupAt?.toISOString()||null,projectDirty:state.projectDirty,dirtySince:state.dirtySince?.toISOString()||null},assets:Object.fromEntries(state.assets.map(a=>[a.uid,{category:a.category,categoryPath:a.categoryPath,categoryLabel:a.categoryLabel,tags:a.tags}]))}}
function categoryPathFromLabel(label){return String(label||"Unknown").split(" > ").map(x=>x.trim()).filter(Boolean)}
function categoryData(v,fallback="Unknown"){const label=String(v?.categoryLabel||v?.category||fallback),path=Array.isArray(v?.categoryPath)&&v.categoryPath.length?v.categoryPath.map(String):categoryPathFromLabel(label);return{label,path}}
function normalizeAssets(data){const list=Array.isArray(data)?data:data.assets;if(!Array.isArray(list))throw Error("assets_index.json 格式不正確");return list.map(a=>{const c=categoryData(a);return{...a,assetPrefix:a.assetPrefix||"",category:c.label,categoryLabel:c.label,categoryPath:c.path,tags:Array.isArray(a.tags)?a.tags:[]}})}
function applyProject(p){if(validCategoryTree(p?.categoryTree)){CATEGORY_TREE=p.categoryTree;CATEGORIES=categoryTreeValues()}if(p?.backupState){state.classificationsSinceBackup=Number(p.backupState.classificationsSinceBackup)||0;state.lastBackupAt=p.backupState.lastBackupAt?new Date(p.backupState.lastBackupAt):null;if(typeof p.backupState.projectDirty==="boolean"){state.projectDirty=p.backupState.projectDirty;state.dirtySince=p.backupState.dirtySince?new Date(p.backupState.dirtySince):null}}if(p?.backupState?.projectDirty===undefined){const saved=p?.savedAt?new Date(p.savedAt):null;if(saved&&!Number.isNaN(saved.getTime())&&(!state.lastBackupAt||saved>state.lastBackupAt)){state.projectDirty=true;state.dirtySince=saved}}const map=Array.isArray(p?.assets)?Object.fromEntries(p.assets.map(a=>[a.uid,a])):p?.assets||p?.classifications||{};state.assets.forEach(a=>{const v=map[a.uid];if(v){const c=categoryData(v,a.category);a.category=c.label;a.categoryLabel=c.label;a.categoryPath=c.path;a.tags=Array.isArray(v.tags)?[...new Set(v.tags.map(String))]:a.tags}})}

function afterLoad(){buildGroups();refreshOptions();state.page=1;applyFilters()}
function spriteRank(name){if(name==="Sprite")return-1;const m=name.match(/^Sprite(\d+)$/);return m?Number(m[1]):999}
function compareAssets(a,b){return(SOURCE_ORDER[a.sourceType]??99)-(SOURCE_ORDER[b.sourceType]??99)||spriteRank(a.spriteName)-spriteRank(b.spriteName)||a.originalNumber-b.originalNumber||(a.assetPrefix||"").localeCompare(b.assetPrefix||"")||(LANG_ORDER[a.lang]??99)-(LANG_ORDER[b.lang]??99)||a.fileName.localeCompare(b.fileName,undefined,{numeric:true})}
function buildGroups(){const map=new Map;for(const a of [...state.assets].sort(compareAssets)){const key=`${a.sourceType}|${a.spriteName}|${a.assetPrefix||""}|${a.originalNumber}`;if(!map.has(key))map.set(key,{key,sourceType:a.sourceType,spriteName:a.spriteName,assetPrefix:a.assetPrefix||"",originalNumber:a.originalNumber,assets:[]});map.get(key).assets.push(a)}state.groups=[...map.values()].sort((a,b)=>(SOURCE_ORDER[a.sourceType]??99)-(SOURCE_ORDER[b.sourceType]??99)||spriteRank(a.spriteName)-spriteRank(b.spriteName)||a.originalNumber-b.originalNumber||a.assetPrefix.localeCompare(b.assetPrefix))}
function refreshOptions(){const sf=$("sourceFilter").value,sp=$("spriteFilter").value,cf=$("categoryFilter").value;fillSelect($("sourceFilter"),uniq(state.assets.map(a=>a.sourceType)));fillSelect($("spriteFilter"),uniq(state.assets.map(a=>a.spriteName),true));fillSelect($("categoryFilter"),uniq([...CATEGORIES,...state.assets.map(a=>a.categoryLabel||a.category)]));$("sourceFilter").value=sf;$("spriteFilter").value=sp;$("categoryFilter").value=cf}
function isUnknown(a){return String(a.categoryLabel||a.category||"Unknown").toLowerCase()==="unknown"}
function applyFilters(){const q=$("search").value.trim().toLowerCase(),src=$("sourceFilter").value,spr=$("spriteFilter").value,lang=$("langFilter").value,cat=$("categoryFilter").value,nums=["minWidth","maxWidth","minHeight","maxHeight"].map(id=>Number($(id).value)||null),catalogUnknown=state.appMode==="catalog"&&state.catalogUnknownOnly,matches=a=>(!catalogUnknown||isUnknown(a))&&(!src||a.sourceType===src)&&(!spr||a.spriteName===spr)&&(!lang||a.lang===lang)&&(!cat||a.category===cat)&&(!nums[0]||a.width>=nums[0])&&(!nums[1]||a.width<=nums[1])&&(!nums[2]||a.height>=nums[2])&&(!nums[3]||a.height<=nums[3])&&(!q||a.fileName.toLowerCase().includes(q)||a.uid.toLowerCase().includes(q));state.visibleAssets=state.assets.filter(matches).sort(compareAssets);window.visibleAssets=state.visibleAssets;const visibleIds=new Set(state.visibleAssets.map(a=>a.uid));state.filtered=state.groups.filter(g=>g.assets.some(a=>visibleIds.has(a.uid)));$("quickSource").value=src;state.page=1;render()}
function clearFilters(){["search","sourceFilter","spriteFilter","langFilter","categoryFilter","minWidth","maxWidth","minHeight","maxHeight"].forEach(id=>$(id).value="");applyFilters()}

function render(){clearURLs();const start=(state.page-1)*PAGE_SIZE,isSerial=state.viewMode==="serial",allItems=isSerial?state.visibleAssets:state.filtered,items=allItems.slice(start,start+PAGE_SIZE),totalAssets=state.visibleAssets.length;$("resultCount").textContent=isSerial?`${totalAssets.toLocaleString()} 張圖片`:`${state.filtered.length.toLocaleString()} 個群組 / ${totalAssets.toLocaleString()} 張圖片`;$("gallery").replaceChildren(...items.map(isSerial?assetCard:groupCard));$("emptyState").classList.toggle("hidden",state.assets.length>0);$("gallery").classList.toggle("hidden",state.assets.length===0);const pages=Math.max(1,Math.ceil(allItems.length/PAGE_SIZE));$("pagination").classList.toggle("hidden",allItems.length<=PAGE_SIZE);$("pageInfo").textContent=`第 ${state.page} / ${pages} 頁`;$("prevPage").disabled=state.page<=1;$("nextPage").disabled=state.page>=pages;const pageAssets=isSerial?items:items.flatMap(g=>g.assets);$("selectPage").checked=pageAssets.length>0&&pageAssets.every(a=>state.selected.has(a.uid));$("selectPage").indeterminate=pageAssets.some(a=>state.selected.has(a.uid))&&!$("selectPage").checked;renderSectionInfo(items);updatePagination(pages);updateSelection()}
function assetCard(a){const card=el("article","card"+(state.selected.has(a.uid)?" selected":"")),thumb=el("div","thumb"),check=document.createElement("input"),badges=el("div","badge-row");card.dataset.key=a.uid;card.onmousedown=e=>{if(e.button===0){e.stopPropagation();selectAssetClick(a,e)}};card.ondblclick=()=>{const g=state.groups.find(x=>x.assets.some(v=>v.uid===a.uid));if(g)openGroup(g)};check.type="checkbox";check.className="pick";check.checked=state.selected.has(a.uid);check.tabIndex=-1;check.onclick=e=>e.preventDefault();thumb.append(check);loadAssetImage(a,thumb);badges.append(el("span","badge",a.lang));thumb.append(badges);card.append(thumb);const info=el("div","card-info");info.append(el("div","card-title",a.fileName));const meta=el("div","meta");meta.append(el("span","",a.sourceType),el("span","",a.spriteName),el("span","",`#${a.originalNumber}`),el("span","",`${a.width}×${a.height}`),el("span","category",a.category));info.append(meta);card.append(info);return card}
function renderSectionInfo(items){const box=$("sectionInfo");box.classList.toggle("hidden",state.viewMode!=="serial"||!items.length);if(state.viewMode!=="serial"||!items.length)return;const first=items[0],same=items.filter(a=>a.sourceType===first.sourceType&&a.spriteName===first.spriteName),min=Math.min(...same.map(a=>a.originalNumber)),max=Math.max(...same.map(a=>a.originalNumber));box.textContent=`${first.sourceType} / ${first.spriteName} / ${min} - ${max}`}
function groupCard(g){const selected=g.assets.filter(a=>state.selected.has(a.uid)).length,card=el("article","card"+(selected?" selected":"")),thumb=el("div","thumb"),check=document.createElement("input");card.dataset.key=g.key;card.onmousedown=e=>{if(e.button===0){e.stopPropagation();selectGroupClick(g,e)}};card.ondblclick=e=>{e.stopPropagation();openGroup(g)};check.type="checkbox";check.className="pick";check.checked=selected===g.assets.length;check.indeterminate=selected>0&&selected<g.assets.length;check.tabIndex=-1;check.onclick=e=>e.preventDefault();thumb.append(check);loadAssetImage(g.assets[0],thumb);const badges=el("div","badge-row");g.assets.forEach(a=>badges.append(el("span","badge",a.lang)));thumb.append(badges);const cats=uniq(g.assets.map(a=>a.category));card.append(thumb);const info=el("div","card-info"),numberLabel=`${g.assetPrefix||""}${g.originalNumber}`;info.append(el("div","card-title",`${numberLabel} · ${g.spriteName}`));const meta=el("div","meta");meta.append(el("span","",g.sourceType),el("span","",`${g.assets.length} 個版本`),el("span","category",cats.length===1?cats[0]:"多種分類"));info.append(meta);card.append(info);return card}
async function loadAssetImage(asset,container){try{const h=await resolveFile(asset.relativePath),f=await h.getFile(),url=URL.createObjectURL(f),img=new Image();state.urls.push(url);img.loading="lazy";img.alt=asset.fileName;img.src=url;container.prepend(img)}catch{container.prepend(el("span","","無法載入"))}}
async function resolveFile(path){let h=state.root;const parts=path.split("/");for(let i=0;i<parts.length-1;i++)h=await h.getDirectoryHandle(parts[i]);return h.getFileHandle(parts.at(-1))}
function clearURLs(){state.urls.forEach(URL.revokeObjectURL);state.urls=[]}
function pageCount(){const total=state.viewMode==="serial"?state.visibleAssets.length:state.filtered.length;return Math.max(1,Math.ceil(total/PAGE_SIZE))}
function setPage(p){state.page=Math.max(1,Math.min(pageCount(),Number(p)||1));render();window.scrollTo({top:0,behavior:"smooth"})}
function jumpToPage(){setPage($("pageInput").value)}
function updatePagination(pages){$("firstPage").disabled=state.page<=1;$("lastPage").disabled=state.page>=pages;$("pageInput").max=pages;$("pageInput").value=state.page}
function togglePageSelection(e){currentPageAssets().forEach(a=>e.target.checked?state.selected.add(a.uid):state.selected.delete(a.uid));render()}

function pageGroups(){return state.filtered.slice((state.page-1)*PAGE_SIZE,state.page*PAGE_SIZE)}
function currentPageAssets(){return state.viewMode==="serial"?state.visibleAssets.slice((state.page-1)*PAGE_SIZE,state.page*PAGE_SIZE):pageGroups().flatMap(g=>g.assets)}
function setGroupSelected(g,on){g.assets.forEach(a=>on?state.selected.add(a.uid):state.selected.delete(a.uid))}
function selectGroupClick(g,e){
  const groups=pageGroups();
  if(e.shiftKey&&state.anchorKey){const a=groups.findIndex(x=>x.key===state.anchorKey),b=groups.findIndex(x=>x.key===g.key);if(a>=0&&b>=0){if(!e.ctrlKey)state.selected.clear();for(let i=Math.min(a,b);i<=Math.max(a,b);i++)setGroupSelected(groups[i],true)}}
  else{const was=g.assets.every(a=>state.selected.has(a.uid));if(!e.ctrlKey)state.selected.clear();setGroupSelected(g,e.ctrlKey?!was:true);state.anchorKey=g.key}
  render();
}
function selectAssetClick(a,e){if(e.shiftKey&&state.anchorKey){const start=state.visibleAssets.findIndex(x=>x.uid===state.anchorKey),end=state.visibleAssets.findIndex(x=>x.uid===a.uid);if(start>=0&&end>=0){if(!e.ctrlKey)state.selected.clear();for(let i=Math.min(start,end);i<=Math.max(start,end);i++)state.selected.add(state.visibleAssets[i].uid)}}else{const was=state.selected.has(a.uid);if(!e.ctrlKey)state.selected.clear();if(!e.ctrlKey||!was)state.selected.add(a.uid);state.anchorKey=a.uid}render()}
function setViewMode(mode){state.viewMode=mode;state.page=1;state.anchorKey=null;$("sourceView").classList.toggle("active",mode==="source");$("serialView").classList.toggle("active",mode==="serial");render()}
function jumpToSprite(name){if(!name){state.page=1;render();return}const list=state.viewMode==="serial"?state.visibleAssets:state.filtered,index=list.findIndex(x=>x.spriteName===name);if(index<0)return showNotice(`目前篩選結果中沒有 ${name}。`,true);state.page=Math.floor(index/PAGE_SIZE)+1;render();window.scrollTo({top:0,behavior:"smooth"})}
function setAppMode(mode){state.appMode=mode;state.page=1;state.anchorKey=null;state.selected.clear();const catalog=mode==="catalog";if(catalog){state.catalogUnknownOnly=true;$("categoryFilter").value="";setViewMode("serial")}$("normalMode").classList.toggle("active",!catalog);$("catalogMode").classList.toggle("active",catalog);$("catalogSidebar").classList.toggle("hidden",!catalog);$("catalogTools").classList.toggle("hidden",!catalog);$("catalogInspector").classList.toggle("hidden",!catalog);$("catalogStatus").classList.toggle("hidden",!catalog);$("main")?.classList.toggle("catalog-mode",catalog);document.querySelector("main.layout").classList.toggle("catalog-mode",catalog);$("toggleUnknown").textContent="只看 Unknown";applyFilters()}
function toggleCatalogUnknown(){state.catalogUnknownOnly=!state.catalogUnknownOnly;$("toggleUnknown").textContent=state.catalogUnknownOnly?"只看 Unknown":"看全部素材";applyFilters()}
function parseSerialRange(text){const m=text.trim().match(/^(\d+)(?:\s*[~\-]\s*(\d+))?$/);if(!m)return null;const a=Number(m[1]),b=m[2]?Number(m[2]):a;return[Math.min(a,b),Math.max(a,b)]}
function selectSerialRange(){const range=parseSerialRange($("serialRange").value);if(!range)return showNotice("範圍格式錯誤，請輸入 100、100-250 或 100~250。",true);state.selected.clear();if(state.viewMode==="serial")state.visibleAssets.filter(a=>a.originalNumber>=range[0]&&a.originalNumber<=range[1]).forEach(a=>state.selected.add(a.uid));else state.filtered.filter(g=>g.originalNumber>=range[0]&&g.originalNumber<=range[1]).forEach(g=>setGroupSelected(g,true));render();showNotice(`已選取流水號 ${range[0]} - ${range[1]} 的 ${state.selected.size} 張素材。`)}
function jumpUnknown(direction){const list=state.visibleAssets.filter(isUnknown);if(!list.length)return showNotice("目前篩選條件中沒有 Unknown 素材。",true);let index=list.findIndex(a=>state.selected.has(a.uid));if(index<0){const pageStart=(state.page-1)*PAGE_SIZE,indexInAll=Math.min(pageStart,state.visibleAssets.length-1),current=state.visibleAssets[indexInAll];index=Math.max(0,list.findIndex(a=>a.uid===current?.uid))}index=Math.max(0,Math.min(list.length-1,index+direction));const target=list[index],visibleIndex=state.visibleAssets.findIndex(a=>a.uid===target.uid);state.page=Math.floor(visibleIndex/PAGE_SIZE)+1;render();focusVisibleAsset(target.uid)}
function focusVisibleAsset(uid){if(!uid)return;requestAnimationFrame(()=>{const card=[...document.querySelectorAll("#gallery .card")].find(x=>x.dataset.key===uid);if(card){card.scrollIntoView({block:"center",behavior:"smooth"});card.classList.add("catalog-focus");setTimeout(()=>card.classList.remove("catalog-focus"),1300)}})}
function startBandSelection(e){
  if(e.button!==0||e.target.closest(".card"))return;
  e.preventDefault();hideContextMenu();const base=e.ctrlKey?new Set(state.selected):new Set();if(!e.ctrlKey)state.selected.clear();
  state.drag={x:e.clientX,y:e.clientY,base};const band=$("selectionBand");band.classList.remove("hidden");
  const move=ev=>{const x=Math.min(state.drag.x,ev.clientX),y=Math.min(state.drag.y,ev.clientY),w=Math.abs(ev.clientX-state.drag.x),h=Math.abs(ev.clientY-state.drag.y),box={left:x,top:y,right:x+w,bottom:y+h};Object.assign(band.style,{left:`${x}px`,top:`${y}px`,width:`${w}px`,height:`${h}px`});state.selected=new Set(state.drag.base);document.querySelectorAll("#gallery .card").forEach(card=>{const r=card.getBoundingClientRect(),hit=r.left<box.right&&r.right>box.left&&r.top<box.bottom&&r.bottom>box.top;if(state.viewMode==="serial"){const a=currentPageAssets().find(v=>v.uid===card.dataset.key);if(hit&&a)state.selected.add(a.uid);card.classList.toggle("selected",!!a&&state.selected.has(a.uid))}else{const g=pageGroups().find(v=>v.key===card.dataset.key);if(hit&&g)setGroupSelected(g,true);card.classList.toggle("selected",!!g&&g.assets.some(a=>state.selected.has(a.uid)))}});updateSelection()};
  const up=()=>{document.removeEventListener("mousemove",move);document.removeEventListener("mouseup",up);band.classList.add("hidden");state.drag=null;render()};document.addEventListener("mousemove",move);document.addEventListener("mouseup",up);
}

function openContextMenu(e){e.preventDefault();const card=e.target.closest(".card");if(card){if(state.viewMode==="serial"){const a=currentPageAssets().find(x=>x.uid===card.dataset.key);if(a&&!state.selected.has(a.uid)){state.selected.clear();state.selected.add(a.uid);state.anchorKey=a.uid;render()}}else{const g=pageGroups().find(x=>x.key===card.dataset.key);if(g&&!g.assets.some(a=>state.selected.has(a.uid))){state.selected.clear();setGroupSelected(g,true);state.anchorKey=g.key;render()}}}if(!state.selected.size)return;const menu=$("contextMenu");menu.style.left=`${Math.min(e.clientX,innerWidth-180)}px`;menu.style.top=`${Math.min(e.clientY,innerHeight-220)}px`;menu.classList.remove("hidden")}
function hideContextMenu(){$("contextMenu").classList.add("hidden")}
function handleContextAction(e){const action=e.target.dataset.action;if(!action)return;hideContextMenu();if(action==="category")$("categoryDialog").showModal();if(action==="tag"){$("dialogTagInput").value="";$("tagDialog").showModal()}if(action==="clear-category")applyCategoryValue("Unknown");if(action==="clear-tags")clearSelectedTags();if(action==="info")showSelectedInfo();if(action==="export-selected")openSelectedMediaExport()}
function buildCategoryTree(){const makeButton=(parent,child,catalog=false)=>{const value=child?`${parent} > ${child}`:parent,b=el("button",catalog?"category-choice":"",child||parent);b.onclick=()=>{state.currentCategory=value;updateSelection();if(state.selected.size)applyCategoryValue(value);if(!catalog)$("categoryDialog").close()};return b},root=$("categoryTree");root.replaceChildren(...Object.entries(CATEGORY_TREE).map(([parent,children])=>{const box=el("section","category-branch"),title=el("h3","",parent);box.append(title);(children.length?children:[""]).forEach(child=>box.append(makeButton(parent,child)));return box}));$("catalogCategoryTree").replaceChildren(...Object.entries(CATEGORY_TREE).map(([parent,children])=>{const details=document.createElement("details"),summary=document.createElement("summary"),label=el("span","",parent),actions=el("span","tree-actions");if(parent!=="Unknown"){const add=el("button","tree-action","＋"),rename=el("button","tree-action","改名");add.title="新增子分類";add.onclick=e=>{e.preventDefault();e.stopPropagation();openCategoryEditor({mode:"add-child",parent})};rename.onclick=e=>{e.preventDefault();e.stopPropagation();openCategoryEditor({mode:"rename-root",parent})};actions.append(add,rename)}summary.append(label,actions);details.open=parent!=="Unknown";details.append(summary);(children.length?children:[""]).forEach(child=>{const row=el("div","tree-leaf");row.append(makeButton(parent,child,true));if(child&&parent!=="Unknown"){const edit=el("button","tree-action","改名");edit.onclick=()=>openCategoryEditor({mode:"rename-child",parent,child});row.append(edit)}details.append(row)});return details}))}

function categoryTreeValues(){return Object.entries(CATEGORY_TREE).flatMap(([parent,children])=>children.length?children.map(child=>`${parent} > ${child}`):[parent])}
function validCategoryTree(tree){return!!tree&&typeof tree==="object"&&!Array.isArray(tree)&&Object.prototype.hasOwnProperty.call(tree,"Unknown")&&Object.entries(tree).every(([k,v])=>k&&Array.isArray(v)&&v.every(x=>typeof x==="string"&&x))}
function openCategoryEditor(config){state.categoryEditor=config;const rename=config.mode.startsWith("rename");$("categoryEditorTitle").textContent=rename?"重新命名分類":config.mode==="add-root"?"新增主分類":"新增子分類";$("categoryParentField").classList.toggle("hidden",config.mode!=="add-child");fillSelect($("categoryParent"),Object.keys(CATEGORY_TREE).filter(x=>x!=="Unknown"),false);if(config.parent)$("categoryParent").value=config.parent;$("categoryName").value=config.child||config.parent||"";$("categoryEditorDialog").showModal();$("categoryName").focus()}
async function saveCategoryEditor(){const cfg=state.categoryEditor,name=$("categoryName").value.trim();if(!cfg||!name||name.includes(">"))return showNotice("分類名稱不可空白，也不能包含 >。",true);if(cfg.mode==="add-root"){if(Object.prototype.hasOwnProperty.call(CATEGORY_TREE,name))return showNotice("已有同名主分類。",true);CATEGORY_TREE[name]=[]}else if(cfg.mode==="add-child"){const parent=$("categoryParent").value;if(!parent||CATEGORY_TREE[parent].includes(name))return showNotice("請選擇上層分類，且名稱不可重複。",true);CATEGORY_TREE[parent].push(name)}else if(cfg.mode==="rename-root"){if(cfg.parent==="Unknown")return;if(name!==cfg.parent&&Object.prototype.hasOwnProperty.call(CATEGORY_TREE,name))return showNotice("已有同名主分類。",true);const next={};for(const [key,value]of Object.entries(CATEGORY_TREE))next[key===cfg.parent?name:key]=value;CATEGORY_TREE=next;migrateCategoryLabels(cfg.parent,name,true)}else if(cfg.mode==="rename-child"){if(name!==cfg.child&&CATEGORY_TREE[cfg.parent].includes(name))return showNotice("此主分類下已有同名分類。",true);CATEGORY_TREE[cfg.parent]=CATEGORY_TREE[cfg.parent].map(x=>x===cfg.child?name:x);migrateCategoryLabels(`${cfg.parent} > ${cfg.child}`,`${cfg.parent} > ${name}`,false)}state.undo=[];state.redo=[];CATEGORIES=categoryTreeValues();buildCategoryTree();refreshCategoryControls();$("categoryEditorDialog").close();applyFilters();await Promise.all([saveSettings(),saveProject()]);showNotice("分類樹已更新並儲存。")}
function migrateCategoryLabels(from,to,includeChildren){state.assets.forEach(a=>{const label=a.categoryLabel||a.category;if(label===from||(includeChildren&&label.startsWith(from+" > "))){const next=to+label.slice(from.length);a.category=next;a.categoryLabel=next;a.categoryPath=categoryPathFromLabel(next)}})}
function refreshCategoryControls(){const batch=$("batchCategory").value,filter=$("categoryFilter").value;fillSelect($("batchCategory"),CATEGORIES,false);fillSelect($("categoryFilter"),uniq([...CATEGORIES,...state.assets.map(a=>a.categoryLabel||a.category)]));if(CATEGORIES.includes(batch))$("batchCategory").value=batch;if([...$("categoryFilter").options].some(o=>o.value===filter))$("categoryFilter").value=filter}
async function saveSettings(){if(!state.root)return;if(!state.projectDirty)state.dirtySince=new Date();state.projectDirty=true;try{const d=await state.root.getDirectoryHandle(".LineageAssetStudio",{create:true});await writeJSON(d,"settings.json",settingsPayload())}catch(e){showNotice(`分類樹設定儲存失敗：${e.message}`,true)}}
function handleKeyboard(e){if(e.target.matches("input,textarea,select")||document.querySelector("dialog[open]"))return;const ctrl=e.ctrlKey||e.metaKey;if(ctrl&&e.key.toLowerCase()==="a"){e.preventDefault();currentPageAssets().forEach(a=>state.selected.add(a.uid));render()}else if(e.key==="Escape"){state.selected.clear();render()}else if(e.key==="Delete"){e.preventDefault();applyCategoryValue("Unknown")}else if(ctrl&&e.key.toLowerCase()==="z"){e.preventDefault();undoCategory()}else if(ctrl&&e.key.toLowerCase()==="y"){e.preventDefault();redoCategory()}else if(e.key.toLowerCase()==="f"&&state.appMode==="catalog"){e.preventDefault();toggleCatalogUnknown()}else if(e.key==="Enter"&&state.selected.size){e.preventDefault();applyCategoryValue(state.currentCategory)}}
function clearSelectedTags(){const list=selectedAssets();if(!list.length)return;list.forEach(a=>a.tags=[]);changed(`${list.length} 張圖片的 Tag 已清除。`)}
function confirmDialogTags(){const tags=$("dialogTagInput").value.split(/[,，]/).map(s=>s.trim()).filter(Boolean);if(!tags.length)return;const list=selectedAssets();list.forEach(a=>a.tags=[...new Set([...a.tags,...tags])]);$("tagDialog").close();changed(`${list.length} 張圖片已加入 Tag。`)}
function showSelectedInfo(){const list=selectedAssets();$("infoSummary").textContent=`共 ${list.length.toLocaleString()} 張圖片`;$("infoContent").textContent=list.slice(0,500).map(a=>`${a.uid}\n  ${a.relativePath}\n  ${a.width}×${a.height}｜${a.category}｜${a.tags.join(", ")||"無 Tag"}`).join("\n\n")+(list.length>500?`\n\n…另有 ${list.length-500} 張未顯示`:"");$("infoDialog").showModal()}

function openGroup(g){clearURLs();$("dialogTitle").textContent=`${g.sourceType} / ${g.spriteName} / ${g.assetPrefix||""}${g.originalNumber}`;$("dialogMeta").textContent=`${g.assets.length} 個語言版本`;$("versionGrid").replaceChildren(...g.assets.map(a=>{const v=el("article","version"),t=el("div","thumb");loadAssetImage(a,t);const f=document.createElement("footer"),lab=document.createElement("label"),c=document.createElement("input");c.type="checkbox";c.checked=state.selected.has(a.uid);c.onchange=()=>{c.checked?state.selected.add(a.uid):state.selected.delete(a.uid);updateSelection()};lab.append(c,document.createTextNode(`${a.lang} · ${a.fileName}`));f.append(lab,el("p","",`${a.width} × ${a.height} · ${a.category}`),el("p","",a.tags.length?`# ${a.tags.join("  # ")}`:"尚無 tags"));v.append(t,f);return v}));$("groupDialog").showModal()}
function closeDialog(){$("groupDialog").close();render()}
function updateSelection(){const count=state.selected.size;$("selectionCount").textContent=`已選 ${count.toLocaleString()} 張圖片`;$("hudCount").textContent=`${count.toLocaleString()} 張`;$("hudCategory").textContent=state.currentCategory;$("selectionHud").classList.toggle("hidden",!count);updateCatalogStatus();updateCatalogInspector()}
function updateCatalogStatus(){if(state.appMode!=="catalog")return;const unknown=state.assets.filter(isUnknown).length;$("statusTotal").textContent=state.assets.length.toLocaleString();$("statusClassified").textContent=(state.assets.length-unknown).toLocaleString();$("statusUnknown").textContent=unknown.toLocaleString();$("statusSelected").textContent=state.selected.size.toLocaleString();$("statusSession").textContent=state.sessionClassified.toLocaleString()}
function updateCatalogInspector(){if(state.appMode!=="catalog")return;const list=selectedAssets();if(!list.length){$("catalogSelectionInfo").textContent="尚未選取素材";return}const first=list[0];$("catalogSelectionInfo").textContent=[`已選取：${list.length} 張`,`UID：${first.uid}`,`檔名：${first.fileName}`,`來源：${first.sourceType} / ${first.spriteName}`,`流水號：${first.originalNumber}`,`語言：${first.lang}`,`尺寸：${first.width} × ${first.height}`,`分類：${first.categoryLabel||first.category}`,`Tags：${first.tags.join(", ")||"無"}`,list.length>1?`\n另有 ${list.length-1} 張已選素材`:""].join("\n")}
function selectedAssets(){return state.assets.filter(a=>state.selected.has(a.uid))}
function applyCategory(){applyCategoryValue($("batchCategory").value)}
function applyCategoryValue(value,record=true){const list=selectedAssets();if(!list.length)return showNotice("請先選取圖片。",true);const oldIndex=Math.max(0,state.visibleAssets.findIndex(a=>state.selected.has(a.uid))),changes=list.filter(a=>(a.categoryLabel||a.category)!==value).map(a=>({uid:a.uid,before:a.categoryLabel||a.category,after:value}));if(!changes.length)return;if(record){state.undo.push(changes);state.redo=[];state.classificationsSinceBackup++}const map=new Map(changes.map(x=>[x.uid,x.after]));state.assets.forEach(a=>{if(map.has(a.uid)){const label=map.get(a.uid);a.category=label;a.categoryLabel=label;a.categoryPath=categoryPathFromLabel(label)}});if(!isUnknown({categoryLabel:value}))state.sessionClassified+=changes.filter(x=>String(x.before).toLowerCase()==="unknown").length;state.currentCategory=value;changed(`${changes.length} 張圖片已套用分類「${value}」。`);if(state.classificationsSinceBackup>=100)createSnapshot("100 次批次分類");if(state.appMode==="catalog"&&!isUnknown({categoryLabel:value})){state.selected.clear();const next=Math.min(oldIndex,Math.max(0,state.visibleAssets.length-1));state.page=Math.floor(next/PAGE_SIZE)+1;render();focusVisibleAsset(state.visibleAssets[next]?.uid)}}
function applyHistory(changes,direction){const map=new Map(changes.map(x=>[x.uid,x[direction]]));state.assets.forEach(a=>{if(map.has(a.uid)){const label=map.get(a.uid);a.category=label;a.categoryLabel=label;a.categoryPath=categoryPathFromLabel(label)}});const delta=changes.reduce((n,x)=>n+(direction==="before"?(String(x.after).toLowerCase()!=="unknown"&&String(x.before).toLowerCase()==="unknown"?-1:0):(String(x.before).toLowerCase()==="unknown"&&String(x.after).toLowerCase()!=="unknown"?1:0)),0);state.sessionClassified=Math.max(0,state.sessionClassified+delta);state.currentCategory=changes.at(-1)?.[direction]||"Unknown";changed(direction==="before"?"已復原上一個分類操作。":"已重做分類操作。")}
function undoCategory(){const changes=state.undo.pop();if(!changes)return;state.redo.push(changes);applyHistory(changes,"before")}
function redoCategory(){const changes=state.redo.pop();if(!changes)return;state.undo.push(changes);applyHistory(changes,"after")}
function addTags(){const tags=$("tagInput").value.split(/[,，]/).map(s=>s.trim()).filter(Boolean),list=selectedAssets();if(!list.length)return showNotice("請先選取圖片。",true);if(!tags.length)return showNotice("請輸入至少一個 tag。",true);list.forEach(a=>a.tags=[...new Set([...a.tags,...tags])]);$("tagInput").value="";changed(`${list.length} 張圖片已加入 tag。`)}
function changed(msg){if(!state.projectDirty)state.dirtySince=new Date();state.projectDirty=true;const page=state.page;buildGroups();applyFilters();state.page=Math.min(page,Math.max(1,Math.ceil(state.filtered.length/PAGE_SIZE)));render();showNotice(msg);clearTimeout(state.saveTimer);state.saveTimer=setTimeout(saveProject,0)}
async function saveProject(){if(!state.root)return;state.savePromise=state.savePromise.then(async()=>{const d=await state.root.getDirectoryHandle(".LineageAssetStudio",{create:true});await writeJSON(d,"project.json",projectPayload())}).catch(e=>showNotice(`自動儲存失敗：${e.message}`,true));return state.savePromise}

async function importProject(e){const file=e.target.files[0];if(!file)return;try{applyProject(JSON.parse(await file.text()));changed("專案分類進度已匯入並儲存。") }catch(err){showNotice(`匯入失敗：${err.message}`,true)}finally{e.target.value=""}}
function exportCSV(){const cols=["uid","sourceType","spriteName","assetPrefix","originalNumber","lang","fileName","relativePath","width","height","category","categoryLabel","categoryPath","tags"],q=v=>`"${String(v??"").replaceAll('"','""')}"`,rows=[cols.join(","),...publicAssets().map(a=>cols.map(k=>q(k==="tags"?a.tags.join("|"):k==="categoryPath"?a.categoryPath.join("|"):a[k])).join(","))];download("assets_index.csv","\ufeff"+rows.join("\r\n"),"text/csv;charset=utf-8")}
function downloadJSON(name,data){download(name,JSON.stringify(data,null,2),"application/json")}
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}

async function openMediaExport(){
  if(!state.root)return showNotice("請先選擇 LineageAssets 資料夾。",true);
  $("mediaExportDialog").showModal();$("mediaFileList").textContent="正在掃描支援的媒體檔案…";state.mediaFiles=[];state.mediaSelected.clear();
  try{await walkMedia(state.root,"",state.mediaFiles);state.mediaFiles.sort((a,b)=>a.path.localeCompare(b.path,undefined,{numeric:true}));const selectedPaths=new Set(selectedAssets().map(a=>a.relativePath.toLowerCase()));state.mediaFiles.forEach(f=>{if(selectedPaths.has(f.path.toLowerCase()))state.mediaSelected.add(f.path)});$("mediaSearch").value="";renderMediaFiles()}catch(e){$("mediaExportDialog").close();showNotice(`媒體掃描失敗：${e.message}`,true)}
}
async function openSelectedMediaExport(){
  const assets=selectedAssets();if(!assets.length)return showNotice("請先選取要匯出的素材。",true);
  $("mediaExportDialog").showModal();$("mediaFileList").textContent="正在準備已選素材…";state.mediaFiles=[];state.mediaSelected.clear();
  try{for(const asset of assets){const handle=await resolveFile(asset.relativePath),ext=fileExtension(asset.fileName);if(MEDIA_EXTS.has(ext))state.mediaFiles.push({name:asset.fileName,path:asset.relativePath,handle,ext})}state.mediaFiles.sort((a,b)=>a.path.localeCompare(b.path,undefined,{numeric:true}));state.mediaFiles.forEach(f=>state.mediaSelected.add(f.path));$("mediaSearch").value="";renderMediaFiles();$("mediaExportSummary").textContent=`已帶入 ${state.mediaFiles.length.toLocaleString()} 個選取素材`}catch(e){$("mediaExportDialog").close();showNotice(`準備匯出失敗：${e.message}`,true)}
}
async function walkMedia(dir,prefix,out){for await(const [name,h] of dir.entries()){if(name===".LineageAssetStudio")continue;const path=prefix?`${prefix}/${name}`:name;if(h.kind==="directory")await walkMedia(h,path,out);else{const ext=fileExtension(name);if(MEDIA_EXTS.has(ext))out.push({name,path,handle:h,ext})}}}
function mediaFiltered(){const q=$("mediaSearch").value.trim().toLowerCase();return q?state.mediaFiles.filter(f=>f.path.toLowerCase().includes(q)):state.mediaFiles}
function renderMediaFiles(){const files=mediaFiltered(),shown=files.slice(0,600),root=$("mediaFileList");root.replaceChildren(...shown.map(f=>{const row=el("label","media-row"),check=document.createElement("input"),name=el("span","",f.name),path=el("code","",f.path);check.type="checkbox";check.checked=state.mediaSelected.has(f.path);check.onchange=()=>{check.checked?state.mediaSelected.add(f.path):state.mediaSelected.delete(f.path);updateMediaCount()};row.append(check,name,path);return row}));if(!files.length)root.append(el("div","media-row","找不到支援的媒體檔案"));if(files.length>shown.length)root.append(el("div","media-row",`僅顯示前 ${shown.length} 筆；可使用搜尋縮小範圍。`));$("mediaExportSummary").textContent=`資料庫內共 ${state.mediaFiles.length.toLocaleString()} 個支援檔案`;updateMediaCount()}
function updateMediaCount(){$("mediaSelectedCount").textContent=`已選 ${state.mediaSelected.size.toLocaleString()} 個`}
function selectAllMedia(){mediaFiltered().forEach(f=>state.mediaSelected.add(f.path));renderMediaFiles()}
async function exportSelectedMedia(){
  const chosen=state.mediaFiles.filter(f=>state.mediaSelected.has(f.path));if(!chosen.length)return showNotice("請先選擇要匯出的媒體檔案。",true);
  let target;try{target=await showDirectoryPicker({mode:"readwrite",id:"lineage-media-export"})}catch(e){if(e.name!=="AbortError")showNotice(e.message,true);return}
  $("confirmMediaExport").disabled=true;let ok=0,failed=[];
  for(const item of chosen){try{const file=await item.handle.getFile(),actual=await detectMediaType(file);if(!sameMediaType(item.ext,actual))throw Error(`內容是 ${actual?.toUpperCase()||"未知格式"}，與副檔名不符`);const toJpg=item.ext==="png"&&$("pngExportFormat").value==="jpg",name=toJpg?replaceExtension(item.name,"jpg"):item.name,output=toJpg?await pngToJpeg(file):file;await writeUniqueFile(target,name,output);ok++}catch(e){failed.push(`${item.path}：${e.message}`)}}
  $("confirmMediaExport").disabled=false;$("mediaExportDialog").close();showNotice(`匯出完成：${ok} 個成功${failed.length?`，${failed.length} 個失敗（詳見瀏覽器主控台）`:""}。`,failed.length>0);if(failed.length)console.warn("媒體匯出失敗",failed)
}
async function chooseMediaImport(){
  if(!state.root)return showNotice("請先選擇 LineageAssets 資料夾。",true);if(!window.showOpenFilePicker)return showNotice("此瀏覽器不支援媒體檔案選擇，請使用 Chrome 或 Edge。",true);
  let handles;try{handles=await showOpenFilePicker({multiple:true,excludeAcceptAllOption:true,types:[{description:"支援的媒體檔案",accept:{"image/png":[".png"],"image/jpeg":[".jpg",".jpeg"],"audio/ogg":[".ogg"],"audio/wav":[".wav"],"audio/mpeg":[".mp3"],"video/mp4":[".mp4"]}}]})}catch(e){if(e.name!=="AbortError")showNotice(e.message,true);return}
  const valid=[],invalid=[];for(const h of handles){const f=await h.getFile(),ext=fileExtension(f.name),actual=await detectMediaType(f);if(MEDIA_EXTS.has(ext)&&sameMediaType(ext,actual))valid.push({handle:h,file:f});else invalid.push(`${f.name}（內容格式：${actual||"無法辨識"}）`)}if(!valid.length)return showNotice(`沒有可匯入的有效媒體檔案。${invalid.length?" 部分檔案內容與副檔名不符。":""}`,true);if(invalid.length)console.warn("已拒絕格式不符的匯入檔案",invalid);
  state.importFiles=valid;state.folderStack=[{handle:state.root,name:state.root.name}];$("importFileSummary").textContent=`準備匯入 ${valid.length} 個檔案${invalid.length?`；已拒絕 ${invalid.length} 個格式不符檔案`:""}`;await renderFolderBrowser();$("mediaImportDialog").showModal()
}
async function renderFolderBrowser(){const current=state.folderStack.at(-1),folders=[];for await(const [name,h] of current.handle.entries())if(h.kind==="directory"&&name!==".LineageAssetStudio")folders.push({name,handle:h});folders.sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true}));$("folderPath").textContent=state.folderStack.map(x=>x.name).join(" / ");$("folderUp").disabled=state.folderStack.length===1;$("folderList").replaceChildren(...folders.map(f=>{const row=el("div","folder-row"),name=el("span","",`📁 ${f.name}`),open=el("button","","開啟");row.append(name,open);row.ondblclick=()=>enterFolder(f);open.onclick=()=>enterFolder(f);return row}),...(folders.length?[]:[el("div","folder-row","此位置沒有子資料夾")]))}
async function enterFolder(folder){state.folderStack.push(folder);await renderFolderBrowser()}
async function folderUp(){if(state.folderStack.length>1){state.folderStack.pop();await renderFolderBrowser()}}
async function createImportFolder(){const name=$("newFolderName").value.trim();if(!name||/[<>:"/\\|?*]/.test(name)||name==="."||name==="..")return showNotice("資料夾名稱無效。",true);try{const h=await state.folderStack.at(-1).handle.getDirectoryHandle(name,{create:true});$("newFolderName").value="";await renderFolderBrowser();showNotice(`已建立資料夾「${name}」。`)}catch(e){showNotice(`建立資料夾失敗：${e.message}`,true)}}
async function importToCurrentFolder(){const target=state.folderStack.at(-1).handle;$("confirmMediaImport").disabled=true;let ok=0,failed=[];for(const item of state.importFiles){try{await writeUniqueFile(target,item.file.name,item.file);ok++}catch(e){failed.push(`${item.file.name}：${e.message}`)}}$("confirmMediaImport").disabled=false;$("mediaImportDialog").close();showNotice(`匯入完成：${ok} 個成功${failed.length?`，${failed.length} 個失敗`:""}。若匯入 PNG 到素材結構，請按「重新掃描」。`,failed.length>0);if(failed.length)console.warn("媒體匯入失敗",failed)}
function fileExtension(name){return(name.split(".").pop()||"").toLowerCase()}
function replaceExtension(name,ext){return name.replace(/\.[^.]+$/,"")+`.`+ext}
function sameMediaType(ext,type){return(ext==="jpg"||ext==="jpeg")?type==="jpg":ext===type}
async function detectMediaType(file){const b=new Uint8Array(await file.slice(0,16).arrayBuffer()),ascii=(s,e)=>String.fromCharCode(...b.slice(s,e));if(b[0]===0x89&&ascii(1,4)==="PNG")return"png";if(b[0]===0xff&&b[1]===0xd8&&b[2]===0xff)return"jpg";if(ascii(0,4)==="OggS")return"ogg";if(ascii(0,4)==="RIFF"&&ascii(8,12)==="WAVE")return"wav";if(ascii(0,3)==="ID3"||(b[0]===0xff&&(b[1]&0xe0)===0xe0))return"mp3";if(ascii(4,8)==="ftyp")return"mp4";return null}
async function pngToJpeg(file){const image=await createImageBitmap(file),canvas=document.createElement("canvas");canvas.width=image.width;canvas.height=image.height;const ctx=canvas.getContext("2d");ctx.fillStyle="#ffffff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0);image.close();return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error("JPG 轉換失敗")),"image/jpeg",0.92))}
async function writeUniqueFile(dir,requestedName,data){const dot=requestedName.lastIndexOf("."),base=dot>0?requestedName.slice(0,dot):requestedName,ext=dot>0?requestedName.slice(dot):"";let name=requestedName,n=1;while(await fileExists(dir,name))name=`${base} (${n++})${ext}`;const h=await dir.getFileHandle(name,{create:true}),w=await h.createWritable();await w.write(data);await w.close();return name}
async function fileExists(dir,name){try{await dir.getFileHandle(name);return true}catch(e){if(e.name==="NotFoundError")return false;throw e}}

async function initializeBackupSystem(){if(!state.root)return;try{const studio=await state.root.getDirectoryHandle(".LineageAssetStudio",{create:true});await studio.getDirectoryHandle("backups",{create:true});$("createBackup").disabled=false;$("viewBackups").disabled=false;await refreshBackupStats()}catch(e){showNotice(`備份功能初始化失敗：${e.message}`,true)}}
function backupTimestamp(date=new Date()){const p=n=>String(n).padStart(2,"0");return`${date.getFullYear()}-${p(date.getMonth()+1)}-${p(date.getDate())}_${p(date.getHours())}-${p(date.getMinutes())}-${p(date.getSeconds())}`}
async function backupDirectory(){const studio=await state.root.getDirectoryHandle(".LineageAssetStudio",{create:true});return studio.getDirectoryHandle("backups",{create:true})}
async function listBackupFiles(){const dir=await backupDirectory(),items=[];for await(const [name,h]of dir.entries()){if(h.kind==="file"&&name.toLowerCase().endsWith(".json")){const file=await h.getFile();items.push({name,handle:h,size:file.size,lastModified:file.lastModified,file})}}return items.sort((a,b)=>b.lastModified-a.lastModified)}
async function refreshBackupStats(){const all=await listBackupFiles(),snapshots=all.filter(x=>/^project_\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}\.json$/.test(x.name));state.backupCount=snapshots.length;if(snapshots.length){const latest=new Date(snapshots[0].lastModified);if(!state.lastBackupAt||latest>state.lastBackupAt)state.lastBackupAt=latest}updateBackupStatus();return all}
function updateBackupStatus(){$("backupStatus").textContent=state.lastBackupAt?`最近備份 ${state.lastBackupAt.toLocaleString()}｜共 ${state.backupCount} 份`:`尚無備份｜共 ${state.backupCount} 份`}
async function uniqueBackupName(dir,prefix="project"){const now=Date.now();for(let i=0;i<120;i++){const name=`${prefix}_${backupTimestamp(new Date(now+i*1000))}.json`;if(!await fileExists(dir,name))return name}throw Error("無法建立唯一備份檔名")}
async function createSnapshot(reason="auto"){
  if(!state.root||state.backupBusy)return;state.backupBusy=true;$("createBackup").disabled=true;
  const oldCount=state.classificationsSinceBackup,oldTime=state.lastBackupAt,oldDirty=state.projectDirty,oldSince=state.dirtySince;
  try{await saveProject();const dir=await backupDirectory(),name=await uniqueBackupName(dir,"project");state.classificationsSinceBackup=0;state.lastBackupAt=new Date();state.projectDirty=false;state.dirtySince=null;await writeJSON(dir,name,{...projectPayload(),snapshot:{reason,createdAt:state.lastBackupAt.toISOString()}});await enforceBackupRetention(dir);await saveProject();await refreshBackupStats();showNotice(`已建立備份：${name}`)}catch(e){state.classificationsSinceBackup=oldCount;state.lastBackupAt=oldTime;state.projectDirty=oldDirty;state.dirtySince=oldSince;showNotice(`建立備份失敗：${e.message}`,true)}finally{state.backupBusy=false;$("createBackup").disabled=false}
}
async function enforceBackupRetention(dir){const files=[];for await(const [name,h]of dir.entries())if(h.kind==="file"&&/^project_\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}\.json$/.test(name)){const f=await h.getFile();files.push({name,time:f.lastModified})}files.sort((a,b)=>b.time-a.time);for(const old of files.slice(20))await dir.removeEntry(old.name)}
async function checkTimedBackup(){if(!state.root||!state.projectDirty||!state.dirtySince||state.backupBusy)return;if(Date.now()-state.dirtySince.getTime()>=30*60*1000)await createSnapshot("30 分鐘自動備份")}
async function openBackupDialog(){$("backupDialog").showModal();$("backupList").textContent="正在讀取備份…";try{const files=await refreshBackupStats();$("backupDialogSummary").textContent=`共 ${files.length} 個備份檔；自動快照最多保留 20 份`;$("backupList").replaceChildren(...files.map(item=>{const row=el("div","backup-row"),name=el("span","",item.name),time=document.createElement("time"),size=el("small","",formatBytes(item.size)),restore=el("button","","還原此備份");time.textContent=new Date(item.lastModified).toLocaleString();restore.onclick=()=>restoreBackup(item);row.append(name,time,size,restore);return row}),...(files.length?[]:[el("div","backup-row","目前沒有備份")]))}catch(e){$("backupList").textContent=`讀取失敗：${e.message}`}}
function formatBytes(bytes){if(bytes<1024)return`${bytes} B`;if(bytes<1048576)return`${(bytes/1024).toFixed(1)} KB`;return`${(bytes/1048576).toFixed(1)} MB`}
async function restoreBackup(item){if(!confirm(`確定還原 ${item.name}？\n目前 project.json 會先建立 emergency backup。`))return;const restoreButtons=$("backupList").querySelectorAll("button");restoreButtons.forEach(b=>b.disabled=true);try{const data=JSON.parse(await item.file.text());if(!data||typeof data.assets!=="object")throw Error("備份格式不正確");await saveProject();const studio=await state.root.getDirectoryHandle(".LineageAssetStudio",{create:true}),dir=await studio.getDirectoryHandle("backups",{create:true}),emergency=await uniqueBackupName(dir,"emergency_backup");await writeJSON(dir,emergency,projectPayload());await writeJSON(studio,"project.json",data);state.assets=normalizeAssets(await readJSON(studio,"assets_index.json"));applyProject(data);state.classificationsSinceBackup=Number(data.backupState?.classificationsSinceBackup)||0;state.lastBackupAt=data.backupState?.lastBackupAt?new Date(data.backupState.lastBackupAt):state.lastBackupAt;state.projectDirty=false;state.dirtySince=null;state.selected.clear();state.undo=[];state.redo=[];CATEGORIES=categoryTreeValues();buildCategoryTree();refreshCategoryControls();await writeJSON(studio,"settings.json",settingsPayload());afterLoad();await refreshBackupStats();$("backupDialog").close();showNotice(`已還原 ${item.name}；還原前資料已保存為 ${emergency}。`)}catch(e){showNotice(`還原備份失敗：${e.message}`,true);restoreButtons.forEach(b=>b.disabled=false)}}

function reportLines(){return state.scanWarnings.length?state.scanWarnings:["沒有無法讀取的檔案或資料夾。"]}
function openReport(){$("reportSearch").value="";renderReport();$("reportDialog").showModal()}
function renderReport(){const q=$("reportSearch").value.trim().toLowerCase(),all=reportLines(),shown=q?all.filter(x=>x.toLowerCase().includes(q)):all;$("reportSummary").textContent=`掃描時間：${state.lastScanAt?.toLocaleString()||"尚未掃描"}｜警告 ${state.scanWarnings.length.toLocaleString()} 筆${q?`｜符合 ${shown.length.toLocaleString()} 筆`:""}`;$("reportContent").textContent=shown.join("\n")}
async function copyReport(){try{await navigator.clipboard.writeText(reportText());$("copyReport").textContent="已複製";setTimeout(()=>$("copyReport").textContent="複製報告",1500)}catch{showNotice("無法使用剪貼簿，請改用下載報告。",true)}}
function downloadReport(){download("lineage_asset_scan_report.txt","\ufeff"+reportText(),"text/plain;charset=utf-8")}
function reportText(){return["Lineage Asset Studio 掃描報告",`時間：${state.lastScanAt?.toLocaleString()||"尚未掃描"}`,`警告數：${state.scanWarnings.length}`,"",...reportLines()].join("\r\n")}

function fillSelect(select,items,numeric=false){const first=select.options[0]?.value===""?select.options[0].cloneNode(true):null;select.replaceChildren(...(first?[first]:[]),...items.sort(numeric?(a,b)=>a.localeCompare(b,undefined,{numeric:true}):undefined).map(v=>new Option(v,v)))}
function uniq(a,numeric=false){return [...new Set(a)].sort(numeric?(x,y)=>x.localeCompare(y,undefined,{numeric:true}):undefined)}
function el(tag,cls="",text=""){const e=document.createElement(tag);e.className=cls;if(text!=="")e.textContent=text;return e}
function showNotice(text,error=false){const n=$("notice");n.textContent=text;n.className="notice"+(error?" error":"");clearTimeout(showNotice.timer);if(!error)showNotice.timer=setTimeout(()=>n.classList.add("hidden"),6000)}
function setBusy(on,text="",ratio=0){$("progress").classList.toggle("hidden",!on);$("progress").querySelector("div").style.width=`${Math.round(ratio*100)}%`;$("progress").querySelector("span").textContent=text;$("chooseFolder").disabled=on;$("rescan").disabled=on||!state.root}
const nextFrame=()=>new Promise(r=>requestAnimationFrame(r));
function db(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbGet(k){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbPut(k,v){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(STORE,"readwrite").objectStore(STORE).put(v,k);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
