"use strict";

let CATEGORY_TREE={"UI":["登入","角色建立","角色選擇","系統","NPC對話","商城","背包","技能欄","按鈕","其他"],"Item":["武器","防具","飾品","卷軸","消耗品","材料","任務","其他"],"Character":["玩家","NPC","怪物","Boss","寵物","其他"],"Effect":["技能","Buff","Debuff","火焰","雷電","冰","其他"],"Map":["其他"],"Unknown":[]};
const NAME_TYPE_TREE={weapon:{label:"武器",children:{katana:"武士刀",one_hand_sword:"單手劍",two_hand_sword:"雙手劍",dagger:"匕首",bow:"弓",spear:"槍／矛",axe:"斧",wand:"魔杖",chain_sword:"鎖鏈劍",other:"其他武器"}},armor:{label:"防具",children:{helmet:"頭盔",body:"盔甲",cloak:"斗篷",gloves:"手套",boots:"長靴",shield:"盾牌",undershirt:"內衣",accessory:"飾品",other:"其他防具"}},item:{label:"道具",children:{consumable:"消耗品",quest:"任務道具",material:"材料",scroll:"卷軸",potion:"藥水",gem:"寶石",currency:"貨幣",box:"箱子／袋子",other:"其他道具"}},monster:{label:"怪物",children:{normal:"一般怪物",boss:"Boss",npc:"NPC",other:"其他"}},skill:{label:"技能",children:{active:"主動技能",passive:"被動技能",buff:"Buff",debuff:"Debuff",other:"其他"}},doll:{label:"魔法娃娃",children:{doll:"娃娃",other:"其他"}},other:{label:"其他",children:{other:"未分類"}}};
let CATEGORIES=categoryTreeValues();
const PAGE_SIZE=60, DB_NAME="LineageAssetStudio", STORE="handles";
const SOURCE_ORDER={IMG:0,TBT:1,PNG:2},LANG_ORDER={KR:0,TW:1,CN:2,JP:3,EN:4};
const MEDIA_EXTS=new Set(["png","jpg","jpeg","ogg","wav","mp3","mp4"]);
const state={root:null,assets:[],groups:[],filtered:[],visibleAssets:[],viewMode:"serial",appMode:"normal",categoryNavFilter:"",catalogUnknownOnly:false,serialRangeMin:null,serialRangeMax:null,sessionClassified:0,selected:new Set(),page:1,urls:[],saveTimer:null,savePromise:Promise.resolve(),scanWarnings:[],lastScanAt:null,anchorKey:null,currentCategory:"Unknown",undo:[],redo:[],drag:null,mediaFiles:[],mediaSelected:new Set(),importFiles:[],folderStack:[],categoryEditor:null,classificationsSinceBackup:0,projectDirty:false,dirtySince:null,lastBackupAt:null,backupCount:0,backupBusy:false,namePickerInput:null,namePickerAsset:null,namesCatalog:{version:1,updatedAt:null,names:{}},referenceCatalog:{version:1,sourceFile:null,sourceVersion:null,importedAt:null,entries:[]}};
const $=id=>document.getElementById(id);

document.addEventListener("DOMContentLoaded",init);
async function init(){
  const savedSidebarWidth=Number(localStorage.getItem("lineageCatalogSidebarWidth"));if(savedSidebarWidth)document.documentElement.style.setProperty("--sidebar-width",`${Math.max(220,Math.min(480,savedSidebarWidth))}px`);
  const savedInspectorWidth=Number(localStorage.getItem("lineageInspectorWidth"));if(savedInspectorWidth)document.documentElement.style.setProperty("--inspector-width",`${Math.max(260,Math.min(520,savedInspectorWidth))}px`);
  fillSelect($("categoryFilter"),CATEGORIES); fillSelect($("batchCategory"),CATEGORIES,false);
  buildCategoryTree();
  buildNameTypeSelects();
  bindEvents();
  setInterval(checkTimedBackup,60000);
  if(!window.showDirectoryPicker){showNotice("此瀏覽器不支援 File System Access API，請使用最新版 Chrome 或 Edge。",true);$("chooseFolder").disabled=true;return;}
  try{const handle=await dbGet("root");if(handle&&await verifyPermission(handle,false)){await openRoot(handle)}}catch(e){console.warn(e)}
}

function bindEvents(){
  $("chooseFolder").onclick=chooseFolder; $("rescan").onclick=()=>scanRoot(true);
  ["search","sourceFilter","spriteFilter","langFilter","categoryFilter","nameStatusFilter","minWidth","maxWidth","minHeight","maxHeight"].forEach(id=>$(id).addEventListener(id==="search"||id.startsWith("min")||id.startsWith("max")?"input":"change",applyFilters));
  $("clearFilters").onclick=clearFilters; $("firstPage").onclick=()=>setPage(1); $("prevPage").onclick=()=>setPage(state.page-1); $("nextPage").onclick=()=>setPage(state.page+1); $("lastPage").onclick=()=>setPage(pageCount()); $("goPage").onclick=jumpToPage; $("pageInput").onkeydown=e=>{if(e.key==="Enter")jumpToPage()};
  $("topFirstPage").onclick=()=>setPage(1); $("topPrevPage").onclick=()=>setPage(state.page-1); $("topNextPage").onclick=()=>setPage(state.page+1); $("topLastPage").onclick=()=>setPage(pageCount()); $("topGoPage").onclick=()=>setPage($("topPageInput").value); $("topPageInput").onkeydown=e=>{if(e.key==="Enter")setPage(e.currentTarget.value)};
  $("selectPage").onchange=togglePageSelection; $("clearSelection").onclick=()=>{state.selected.clear();render();updateSelection()};
  $("applyCategory").onclick=applyCategory; $("addTags").onclick=addTags;
  $("batchCategory").onchange=()=>{state.currentCategory=$("batchCategory").value;updateSelection()};
  $("exportJson").onclick=()=>downloadJSON("assets_index.json",publicAssets()); $("exportCsv").onclick=exportCSV;
  $("exportProject").onclick=()=>downloadJSON("lineage_asset_project.json",projectPayload()); $("importProject").onchange=importProject;
  $("closeDialog").onclick=()=>closeDialog(); $("groupDialog").addEventListener("click",e=>{if(e.target===$("groupDialog"))closeDialog()});
  $("scanReport").onclick=openReport; $("closeReport").onclick=()=>$("reportDialog").close(); $("reportSearch").oninput=renderReport; $("copyReport").onclick=copyReport; $("downloadReport").onclick=downloadReport;
  $("gallery").addEventListener("mousedown",startBandSelection); $("gallery").addEventListener("contextmenu",openContextMenu);
  document.addEventListener("keydown",handleKeyboard); document.addEventListener("click",e=>{if(!$("contextMenu").contains(e.target))hideContextMenu();if(!$("categoryContextMenu").contains(e.target))hideTreeContextMenu()});
  $("contextMenu").addEventListener("click",handleContextAction); $("confirmTags").onclick=confirmDialogTags;
  document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).close());
  $("sourceView").onclick=()=>setViewMode("source"); $("serialView").onclick=()=>setViewMode("serial"); $("categoryView").onclick=()=>setViewMode("category");
  $("quickSource").onchange=()=>{$("sourceFilter").value=$("quickSource").value;applyFilters()};
  $("quickSprite").onchange=()=>jumpToSprite($("quickSprite").value);
  $("exportMedia").onclick=openMediaExport; $("importMedia").onclick=chooseMediaImport; $("mediaSearch").oninput=renderMediaFiles;
  $("selectAllMedia").onclick=selectAllMedia; $("clearMediaSelection").onclick=()=>{state.mediaSelected.clear();renderMediaFiles()}; $("confirmMediaExport").onclick=exportSelectedMedia;
  $("folderUp").onclick=folderUp; $("createFolder").onclick=createImportFolder; $("confirmMediaImport").onclick=importToCurrentFolder;
  $("normalMode").onclick=()=>setAppMode("normal"); $("catalogMode").onclick=()=>setAppMode("catalog");
  $("applySerialRange").onclick=applySerialRangeFilter; $("clearSerialRange").onclick=clearSerialRangeFilter; ["serialRangeStart","serialRangeEnd"].forEach(id=>$(id).onkeydown=e=>{if(e.key==="Enter")applySerialRangeFilter()});
  $("previousUnknown").onclick=()=>jumpUnknown(-1); $("nextUnknown").onclick=()=>jumpUnknown(1); $("toggleUnknown").onclick=toggleCatalogUnknown; $("topToggleClassified").onclick=toggleCatalogUnknown;
  $("addRootCategory").onclick=()=>openCategoryEditor({mode:"add-root"}); $("saveCategoryEditor").onclick=saveCategoryEditor; $("categoryName").onkeydown=e=>{if(e.key==="Enter")saveCategoryEditor()};
  $("categoryTreeSearch").oninput=buildCategoryTree; $("categoryContextMenu").onclick=handleTreeContextAction; $("sidebarResizer").onmousedown=startSidebarResize;
  $("rightPanelResizer").onmousedown=startRightPanelResize;
  $("catalogCategoryTree").addEventListener("click",e=>{const summary=e.target.closest("summary");if(summary&&e.clientX-summary.getBoundingClientRect().left<24){e.preventDefault();e.stopImmediatePropagation();summary.parentElement.open=!summary.parentElement.open}},true);
  $("createBackup").onclick=()=>createSnapshot("manual"); $("viewBackups").onclick=openBackupDialog;
  $("importNameZip").onchange=importNameReferenceZip; $("applyAssetName").onclick=applyNameFromInspector; $("renameCatalogName").onclick=renameSelectedCatalogName; $("clearAssetName").onclick=clearSelectedNames; $("nameTypeFilter").onchange=renderNameReferenceList; $("assetNameInput").oninput=renderNameReferenceList;
  $("namePickerType").onchange=renderNamePicker; $("namePickerSearch").oninput=renderNamePicker; $("closeNamePicker").onclick=closeNamePicker; $("updateNameClass").onclick=updateSelectedNameClassification;
}

async function chooseFolder(){
  try{const handle=await showDirectoryPicker({mode:"readwrite",id:"lineage-assets"});if(!await verifyPermission(handle,true))throw Error("需要資料夾讀寫權限，才能儲存專案索引。");await dbPut("root",handle);await openRoot(handle)}catch(e){if(e.name!=="AbortError")showNotice(e.message,true)}
}
async function verifyPermission(h,ask){const opts={mode:"readwrite"};if(await h.queryPermission(opts)==="granted")return true;return ask&&(await h.requestPermission(opts)==="granted")}
async function openRoot(handle){
  state.root=handle;$("folderStatus").textContent=`已開啟：${handle.name}`;$("rescan").disabled=false;
  try{const studio=await handle.getDirectoryHandle(".LineageAssetStudio");const idx=await readJSON(studio,"assets_index.json");state.assets=normalizeAssets(idx);try{const p=await readJSON(studio,"project.json");applyProject(p);state.classificationsSinceBackup=Number(p.backupState?.classificationsSinceBackup)||0;state.lastBackupAt=p.backupState?.lastBackupAt?new Date(p.backupState.lastBackupAt):null}catch{}try{const s=await readJSON(studio,"settings.json");state.scanWarnings=Array.isArray(s.scanWarnings)?s.scanWarnings:[];state.lastScanAt=s.lastScan?new Date(s.lastScan):null;if(validCategoryTree(s.categoryTree)){CATEGORY_TREE=s.categoryTree;CATEGORIES=categoryTreeValues();buildCategoryTree();refreshCategoryControls()}$("scanReport").disabled=!state.lastScanAt}catch{}await initializeBackupSystem();showNotice(`已載入現有索引，共 ${state.assets.length.toLocaleString()} 張圖片。`);afterLoad()}catch(e){if(e.name==="NotFoundError")await scanRoot(true);else showNotice(`索引讀取失敗：${e.message}`,true)}
}

async function scanRoot(){
  if(!state.root)return;
  const previous=Object.fromEntries(state.assets.map(a=>[a.uid,{category:a.category,categoryLabel:a.categoryLabel,categoryPath:a.categoryPath,tags:a.tags,nameId:a.nameId,nameStatus:a.nameStatus,nameSource:a.nameSource,nameConfidence:a.nameConfidence}]));
  setBusy(true,"正在尋找 PNG…",0);state.assets=[];state.selected.clear();
  try{
    const found=[],warnings=[];state.scanWarnings=warnings;state.lastScanAt=new Date();
    await walk(state.root,"",found,warnings);
    if(!found.length)throw Error("在 01.IMG、02.TBT、03.PNG 結構中找不到可讀取的 PNG");
    let done=0,skipped=0;
    for(const item of found){
      const parsed=parsePath(item.path);
      if(!parsed){skipped++;warnings.push(`${item.path}：路徑或檔名不符合索引規則`);continue}
      try{
        const file=await item.handle.getFile(),size=await imageSize(file),old=previous[parsed.uid];
        const inferred=parsed.assetPrefix==="ms"?"Character > 怪物":parsed.assetPrefix==="ge"?"Effect > 其他":"Unknown";
        const label=old?.categoryLabel||old?.category||inferred,path=old?.categoryPath||categoryPathFromLabel(label);
        state.assets.push({...parsed,fileName:file.name,relativePath:item.path,width:size.width,height:size.height,category:label,categoryLabel:label,categoryPath:path,tags:old?.tags||[],nameId:old?.nameId||null,nameStatus:old?.nameStatus||"unassigned",nameSource:old?.nameSource||null,nameConfidence:Number(old?.nameConfidence)||0});
      }catch(e){skipped++;warnings.push(`${item.path}：${e.message}`)}
      done++;
      if(done%20===0||done===found.length){setBusy(true,`正在建立索引 ${done.toLocaleString()} / ${found.length.toLocaleString()}（略過 ${skipped.toLocaleString()}）`,found.length?done/found.length:1);await nextFrame()}
    }
    if(!state.assets.length)throw Error("找到 PNG，但路徑或檔名不符合預期格式（例如 77c.png 或 ms1039.png）");
    state.assets.sort((a,b)=>a.sourceType.localeCompare(b.sourceType)||a.spriteName.localeCompare(b.spriteName,undefined,{numeric:true})||a.originalNumber-b.originalNumber||a.lang.localeCompare(b.lang));
    await createStudioFiles();await initializeBackupSystem();afterLoad();
    const suffix=skipped||warnings.length?`，略過 ${skipped.toLocaleString()} 個不符合命名規則或無法讀取的檔案／資料夾。`:"。";
    showNotice(`掃描完成，共建立 ${state.assets.length.toLocaleString()} 張圖片的索引${suffix}`,warnings.length>0);
    $("scanReport").disabled=false;
    if(warnings.length)console.warn("Lineage Asset Studio 掃描警告：",warnings);
  }catch(e){
    const detail=e?.message||String(e);
    showNotice(`掃描失敗：${detail}。請確認選擇的是 LineageAssets 根目錄，且瀏覽器已取得讀寫權限。`,true);
    console.error("Lineage Asset Studio 掃描失敗",e);
  }finally{setBusy(false)}
}
async function walk(dir,prefix,out,warnings){
  try{
    for await(const [name,h] of dir.entries()){
      if(name===".LineageAssetStudio")continue;
      const p=prefix?`${prefix}/${name}`:name;
      if(h.kind==="directory")await walk(h,p,out,warnings);
      else if(name.toLowerCase().endsWith(".png"))out.push({path:p,handle:h});
    }
  }catch(e){if(!prefix)throw e;warnings.push(`${prefix}：${e.message}`)}
}
function parsePath(path){const parts=path.split("/");if(parts.length<3)return null;const types={"01.IMG":"IMG","02.TBT":"TBT","03.PNG":"PNG"};const sourceType=types[parts[0]];if(!sourceType)return null;const file=parts.at(-1),m=file.match(/^(cs|ms|ge)?(\d+)([chej])?\.png$/i);if(!m)return null;const spriteName=parts.at(-2),assetPrefix=(m[1]||"").toLowerCase(),originalNumber=Number(m[2]),suffix=(m[3]||"").toLowerCase(),langs={c:"TW",h:"CN",j:"JP",e:"EN"},lang=langs[suffix]||"KR",prefixUid=assetPrefix?`_${assetPrefix.toUpperCase()}`:"";return{uid:`${sourceType}_${spriteName}${prefixUid}_${originalNumber}_${lang}`,sourceType,spriteName,assetPrefix,originalNumber,lang}}
async function imageSize(file){try{const b=await createImageBitmap(file);const s={width:b.width,height:b.height};b.close();return s}catch{return await new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{resolve({width:im.naturalWidth,height:im.naturalHeight});URL.revokeObjectURL(u)};im.onerror=()=>{URL.revokeObjectURL(u);reject(Error(`無法讀取圖片：${file.name}`))};im.src=u})}}

function settingsPayload(){return{version:2,groupByOriginalNumber:true,pageSize:PAGE_SIZE,lastScan:(state.lastScanAt||new Date()).toISOString(),scanWarnings:state.scanWarnings,categoryTree:CATEGORY_TREE}}
async function createStudioFiles(){const d=await state.root.getDirectoryHandle(".LineageAssetStudio",{create:true});await d.getDirectoryHandle("thumbnails",{create:true});await d.getDirectoryHandle("cache",{create:true});await d.getDirectoryHandle("backups",{create:true});const data=await d.getDirectoryHandle("data",{create:true});await writeJSON(d,"assets_index.json",indexAssets());await writeJSON(d,"project.json",projectPayload());await writeJSON(d,"settings.json",settingsPayload());await writeJSON(data,"names_catalog.json",state.namesCatalog);await writeJSON(data,"reference_catalog.json",state.referenceCatalog)}
async function writeJSON(dir,name,data){const h=await dir.getFileHandle(name,{create:true}),w=await h.createWritable();await w.write(JSON.stringify(data,null,2));await w.close()}
async function readJSON(dir,name){const h=await dir.getFileHandle(name),f=await h.getFile();return JSON.parse(await f.text())}
async function loadNameData(studio){const data=await studio.getDirectoryHandle("data",{create:true});try{const n=await readJSON(data,"names_catalog.json");if(n?.names)state.namesCatalog=n}catch{await writeJSON(data,"names_catalog.json",state.namesCatalog)}try{const r=await readJSON(data,"reference_catalog.json");if(Array.isArray(r?.entries))state.referenceCatalog=r}catch{await writeJSON(data,"reference_catalog.json",state.referenceCatalog)}refreshNameSuggestions();updateReferenceStatus()}
async function saveNameData(){if(!state.root)return;const studio=await state.root.getDirectoryHandle(".LineageAssetStudio",{create:true}),data=await studio.getDirectoryHandle("data",{create:true});state.namesCatalog.updatedAt=new Date().toISOString();await writeJSON(data,"names_catalog.json",state.namesCatalog);await writeJSON(data,"reference_catalog.json",state.referenceCatalog)}
function resolvedName(asset){return asset?.nameId?state.namesCatalog.names[asset.nameId]?.label||null:null}
function normalizeName(value){return String(value||"").trim().normalize("NFKC").toLocaleLowerCase("zh-Hant")}
function hashText(value){let h=2166136261;for(const ch of value){h^=ch.codePointAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
function nameTypeFromPath(path){const p=path.toLowerCase();if(p.includes("/items/"))return"item";if(p.includes("/monsters/"))return"monster";if(p.includes("/skills/"))return"skill";if(p.includes("/doll/"))return"doll";if(p.includes("/weapons/"))return"weapon";if(p.includes("/armor"))return"armor";return"other"}
function inferNameSubtype(type,label,path=""){const text=`${label||""} ${path||""}`;if(type==="weapon"){if(/鎖鏈劍/.test(text))return"chain_sword";if(/魔杖|法杖|權杖/.test(text))return"wand";if(/雙手劍|巨劍|大劍/.test(text))return"two_hand_sword";if(/武士刀|太刀/.test(text))return"katana";if(/匕首|短劍/.test(text))return"dagger";if(/弓/.test(text))return"bow";if(/槍|矛/.test(text))return"spear";if(/斧/.test(text))return"axe";if(/劍|刀/.test(text))return"one_hand_sword"}if(type==="armor"){if(/頭盔|頭箍|帽/.test(text))return"helmet";if(/斗篷|披風/.test(text))return"cloak";if(/手套|腕甲/.test(text))return"gloves";if(/靴|鞋/.test(text))return"boots";if(/盾/.test(text))return"shield";if(/內衣/.test(text))return"undershirt";if(/戒指|項鍊|耳環|腰帶|護身符/.test(text))return"accessory";if(/盔甲|鎧甲|胸甲|戰甲|長袍/.test(text))return"body"}if(type==="item"){if(/卷軸|卷軸/.test(text))return"scroll";if(/藥水|藥劑|靈藥/.test(text))return"potion";if(/任務|證明|信件|密令/.test(text))return"quest";if(/材料|礦石|碎片|結晶|木材|皮革/.test(text))return"material";if(/寶石|鑽石|紅寶石|藍寶石|綠寶石/.test(text))return"gem";if(/金幣|貨幣|代幣|硬幣/.test(text))return"currency";if(/箱|袋|包/.test(text))return"box";if(/食物|水果|料理|飲料/.test(text))return"consumable"}if(type==="monster"){if(/boss|首領|王$/i.test(text))return"boss";if(/npc/i.test(text))return"npc";return"normal"}if(type==="skill"){if(/debuff|弱化/i.test(text))return"debuff";if(/buff|強化/i.test(text))return"buff";if(/被動/.test(text))return"passive";return"active"}if(type==="doll")return"doll";return"other"}
function findNameRecord(label){const key=normalizeName(label);return Object.values(state.namesCatalog.names).find(n=>normalizeName(n.label)===key||(n.aliases||[]).some(a=>normalizeName(a)===key))}
function ensureNameRecord(label,reference=null){let record=findNameRecord(label);if(record)return record;const type=reference?.type||"other",subtype=reference?.subtype||inferNameSubtype(type,label,reference?.path)||"other",nameId=`${type}_${hashText(`${label}|${reference?.path||"manual"}`)}`;record={nameId,label:String(label).trim(),aliases:[],type,subtype,categoryPath:[],source:reference?"reference":"manual",sourceRefs:reference?[{referenceId:reference.referenceId,path:reference.path,sourceFile:state.referenceCatalog.sourceFile}]:[],confirmed:!reference,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};state.namesCatalog.names[nameId]=record;return record}
function refreshNameSuggestions(){for(const r of state.referenceCatalog.entries||[]){if(!NAME_TYPE_TREE[r.type])r.type="other";if(!r.subtype||r.subtype==="other")r.subtype=inferNameSubtype(r.type,r.label,r.path)}for(const n of Object.values(state.namesCatalog.names)){if(!NAME_TYPE_TREE[n.type])n.type="other";if(!n.subtype||n.subtype==="other")n.subtype=inferNameSubtype(n.type,n.label,n.sourceRefs?.[0]?.path);if(!NAME_TYPE_TREE[n.type].children[n.subtype])n.subtype="other"}renderNameReferenceList()}
function nameTypeLabel(type,subtype=null){const group=NAME_TYPE_TREE[type]||NAME_TYPE_TREE.other;if(!subtype)return group.label;return`${group.label} > ${group.children[subtype]||group.children.other||"其他"}`}
function nameClassMatches(item,value){if(!value)return true;const [type,subtype]=value.split(":");return item.type===type&&(!subtype||item.subtype===subtype)}
function buildNameTypeSelects(){const build=(select,all=true,parents=true)=>{const nodes=[];if(all)nodes.push(new Option("全部名稱分類",""));for(const [type,group]of Object.entries(NAME_TYPE_TREE)){if(parents)nodes.push(new Option(`全部${group.label}`,type));const opt=document.createElement("optgroup");opt.label=group.label;for(const [subtype,label]of Object.entries(group.children))opt.append(new Option(label,`${type}:${subtype}`));nodes.push(opt)}select.replaceChildren(...nodes)};build($("nameTypeFilter"),true,true);build($("namePickerType"),true,true);build($("nameClassEditor"),false,false)}
function renderNameReferenceList(){const root=$("nameReferenceList");if(!root)return;const type=$("nameTypeFilter").value,q=normalizeName($("assetNameInput").value),items=allNameCandidates().filter(x=>nameClassMatches(x,type)&&(!q||normalizeName(x.label).includes(q))).sort((a,b)=>a.type.localeCompare(b.type)||a.subtype.localeCompare(b.subtype)||a.label.localeCompare(b.label,"zh-Hant")).slice(0,300);root.replaceChildren(...items.map(item=>{const b=el("button","name-reference-item");b.type="button";b.append(el("span","",item.label),el("small","",`${nameTypeLabel(item.type,item.subtype)} · ${item.source}`));b.onclick=()=>{const assets=selectedAssets();$("assetNameInput").value=item.label;if(assets.length)assignNameToAssets(item.label,assets);else renderNameReferenceList()};return b}),...(items.length?[]:[el("div","name-reference-empty","此分類沒有符合的名稱")]))}
function allNameCandidates(){const map=new Map();for(const r of state.referenceCatalog.entries||[]){const subtype=r.subtype||"other";if(!map.has(`${r.type}|${subtype}|${normalizeName(r.label)}`))map.set(`${r.type}|${subtype}|${normalizeName(r.label)}`,{label:r.label,type:r.type,subtype,source:"ZIP"})}for(const n of Object.values(state.namesCatalog.names)){const type=n.type||"other",subtype=n.subtype||"other";map.set(`${type}|${subtype}|${normalizeName(n.label)}`,{label:n.label,type,subtype,source:n.confirmed?"已確認":"名稱庫"})}return[...map.values()]}
function suggestedNameType(asset){const label=asset?.categoryLabel||asset?.category||"";if(label.startsWith("Item >"))return"item";if(label.includes("怪物")||label.includes("Boss"))return"monster";if(label.includes("技能"))return"skill";if(label.includes("武器"))return"weapon";if(label.includes("防具"))return"armor";return""}
function openNamePicker(input,asset){state.namePickerInput=input;state.namePickerAsset=asset;const picker=$("namePicker"),rect=input.getBoundingClientRect(),record=state.namesCatalog.names[asset.nameId];$("namePickerType").value=record?`${record.type||"other"}:${record.subtype||"other"}`:suggestedNameType(asset);$("namePickerSearch").value="";picker.classList.remove("hidden");const width=Math.min(360,innerWidth-20),left=Math.max(10,Math.min(rect.left,innerWidth-width-10)),height=Math.min(520,innerHeight-20),top=rect.bottom+6+height<=innerHeight?rect.bottom+6:Math.max(10,rect.top-height-6);picker.style.left=`${left}px`;picker.style.top=`${top}px`;renderNamePicker()}
function closeNamePicker(){$("namePicker").classList.add("hidden");state.namePickerInput=null;state.namePickerAsset=null}
function renderNamePicker(){const root=$("namePickerList");if(!root)return;const type=$("namePickerType").value,q=normalizeName($("namePickerSearch").value),items=allNameCandidates().filter(x=>nameClassMatches(x,type)&&(!q||normalizeName(x.label).includes(q))).sort((a,b)=>a.type.localeCompare(b.type)||a.subtype.localeCompare(b.subtype)||a.label.localeCompare(b.label,"zh-Hant")).slice(0,500),nodes=[];let group=null;for(const item of items){const groupKey=`${item.type}:${item.subtype}`;if(groupKey!==group){group=groupKey;nodes.push(el("div","name-picker-group",nameTypeLabel(item.type,item.subtype)))}const b=el("button","name-picker-item");b.type="button";b.append(el("span","",item.label),el("small","",item.source));b.onclick=()=>{const input=state.namePickerInput,asset=state.namePickerAsset;if(input)input.value=item.label;closeNamePicker();if(asset)assignNameToAssets(item.label,[asset])};nodes.push(b)}root.replaceChildren(...nodes,...(items.length?[]:[el("div","name-reference-empty","此分類沒有符合的名稱")]))}
function updateReferenceStatus(){const r=state.referenceCatalog;$("referenceStatus").textContent=r?.sourceFile?`${r.sourceFile}${r.sourceVersion?`｜${r.sourceVersion}`:""}｜${r.entries.length.toLocaleString()} 個名稱`:`尚未匯入名稱資料庫`}
async function assignNameToAssets(label,assets){label=String(label||"").trim();if(!label||!assets.length)return;const reference=(state.referenceCatalog.entries||[]).find(r=>normalizeName(r.label)===normalizeName(label)),record=ensureNameRecord(label,reference||null);record.confirmed=true;record.updatedAt=new Date().toISOString();assets.forEach(a=>{a.nameId=record.nameId;a.nameStatus="confirmed";a.nameSource=reference?"reference":"manual";a.nameConfidence=1});await saveNameData();changed(`${assets.length} 張素材已命名為「${record.label}」。`)}
function applyNameFromInspector(){assignNameToAssets($("assetNameInput").value,selectedAssets())}
async function clearSelectedNames(){const list=selectedAssets();if(!list.length)return showNotice("請先選取素材。",true);list.forEach(a=>{a.nameId=null;a.nameStatus="unassigned";a.nameSource=null;a.nameConfidence=0});changed(`${list.length} 張素材的名稱關聯已清除。`)}
async function renameSelectedCatalogName(){const list=selectedAssets(),ids=[...new Set(list.map(a=>a.nameId).filter(Boolean))],label=$("assetNameInput").value.trim();if(ids.length!==1)return showNotice("全域改名需要所選素材使用同一個名稱。",true);if(!label)return showNotice("請輸入新名稱。",true);const record=state.namesCatalog.names[ids[0]];if(!record)return;const existing=findNameRecord(label);if(existing&&existing.nameId!==record.nameId)return showNotice("已有相同名稱；請改用「套用名稱」建立關聯。",true);if(record.label!==label){record.aliases=[...new Set([...(record.aliases||[]),record.label])];record.label=label;record.updatedAt=new Date().toISOString();await saveNameData();refreshNameSuggestions();changed(`名稱已全域改為「${label}」，舊名稱已保留為別名。`)}}
async function updateSelectedNameClassification(){const ids=[...new Set(selectedAssets().map(a=>a.nameId).filter(Boolean))];if(ids.length!==1)return showNotice("請選取使用同一名稱的素材。",true);const value=$("nameClassEditor").value,[type,subtype]=value.split(":"),record=state.namesCatalog.names[ids[0]];if(!record||!type||!subtype)return;record.type=type;record.subtype=subtype;record.updatedAt=new Date().toISOString();await saveNameData();refreshNameSuggestions();state.projectDirty=true;state.dirtySince=state.dirtySince||new Date();await saveProject();updateCatalogInspector();showNotice(`名稱「${record.label}」已分類為 ${nameTypeLabel(type,subtype)}。`)}
function nameInputForAsset(asset){const input=document.createElement("input");input.className="asset-name-field";input.placeholder="選擇／輸入名稱";input.value=resolvedName(asset)||"";input.onmousedown=e=>e.stopPropagation();input.ondblclick=e=>e.stopPropagation();input.onfocus=()=>openNamePicker(input,asset);input.onkeydown=e=>{e.stopPropagation();if(e.key==="Enter"){e.preventDefault();if(input.value.trim())assignNameToAssets(input.value,[asset]);closeNamePicker();input.blur()}if(e.key==="Escape"){closeNamePicker();input.blur()}};input.onchange=()=>{if(input.value.trim())assignNameToAssets(input.value,[asset]);else{asset.nameId=null;asset.nameStatus="unassigned";asset.nameSource=null;asset.nameConfidence=0;changed("素材名稱已清除。")} };return input}
async function importNameReferenceZip(e){const file=e.target.files[0];if(!file)return;e.target.value="";try{showNotice("正在解析名稱資料庫 ZIP…");await createSnapshot("匯入名稱資料庫前");const entries=await readZipEntries(file),refs=[],seen=new Set();let sourceVersion=null;for(const entry of entries){const lower=entry.name.toLowerCase();if(lower.endsWith("/js/00-data.js")){const text=new TextDecoder("utf-8").decode(await extractZipEntry(entry));sourceVersion=text.match(/GAME_VERSION\s*=\s*['\"]([^'\"]+)/)?.[1]||null}if(!/\.(png|jpe?g)$/i.test(entry.name))continue;const filename=entry.name.split("/").pop(),label=filename.replace(/\.[^.]+$/,"").trim();if(!label||seen.has(entry.name))continue;seen.add(entry.name);refs.push({referenceId:entry.name,label,type:nameTypeFromPath(entry.name),path:entry.name,extension:fileExtension(filename)})}state.referenceCatalog={version:1,sourceFile:file.name,sourceVersion,importedAt:new Date().toISOString(),entries:refs};await saveNameData();state.projectDirty=true;state.dirtySince=state.dirtySince||new Date();await saveProject();refreshNameSuggestions();updateReferenceStatus();showNotice(`名稱資料庫匯入完成：${refs.length.toLocaleString()} 個圖片名稱。`)}catch(err){showNotice(`名稱資料庫 ZIP 匯入失敗：${err.message}`,true)}}
async function readZipEntries(file){const buffer=await file.arrayBuffer(),view=new DataView(buffer),bytes=new Uint8Array(buffer);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(view.getUint32(i,true)===0x06054b50){eocd=i;break}if(eocd<0)throw Error("找不到 ZIP 目錄");const total=view.getUint16(eocd+10,true),offset=view.getUint32(eocd+16,true),decoder=new TextDecoder("utf-8"),entries=[];let p=offset;for(let i=0;i<total;i++){if(view.getUint32(p,true)!==0x02014b50)throw Error("ZIP 目錄格式不正確");const method=view.getUint16(p+10,true),compressedSize=view.getUint32(p+20,true),size=view.getUint32(p+24,true),nameLength=view.getUint16(p+28,true),extraLength=view.getUint16(p+30,true),commentLength=view.getUint16(p+32,true),localOffset=view.getUint32(p+42,true),name=decoder.decode(bytes.slice(p+46,p+46+nameLength));entries.push({name,method,compressedSize,size,localOffset,buffer});p+=46+nameLength+extraLength+commentLength}return entries}
async function extractZipEntry(entry){const view=new DataView(entry.buffer),bytes=new Uint8Array(entry.buffer),p=entry.localOffset;if(view.getUint32(p,true)!==0x04034b50)throw Error("ZIP 項目格式不正確");const nameLength=view.getUint16(p+26,true),extraLength=view.getUint16(p+28,true),start=p+30+nameLength+extraLength,compressed=bytes.slice(start,start+entry.compressedSize);if(entry.method===0)return compressed;if(entry.method!==8)throw Error(`不支援 ZIP 壓縮方式 ${entry.method}`);if(!window.DecompressionStream)throw Error("瀏覽器不支援 ZIP 解壓縮，請更新 Chrome 或 Edge");const stream=new Blob([compressed]).stream().pipeThrough(new DecompressionStream("deflate-raw"));return new Uint8Array(await new Response(stream).arrayBuffer())}
function publicAssets(){return state.assets.map(({uid,sourceType,spriteName,assetPrefix,originalNumber,lang,fileName,relativePath,width,height,category,categoryPath,categoryLabel,tags,nameId,nameStatus,nameSource,nameConfidence})=>({uid,sourceType,spriteName,assetPrefix:assetPrefix||"",originalNumber,lang,fileName,relativePath,width,height,category,categoryPath,categoryLabel,tags,nameId:nameId||null,nameStatus:nameStatus||"unassigned",nameSource:nameSource||null,nameConfidence:nameConfidence||0}))}
function indexAssets(){return publicAssets().map(a=>({...a,category:"Unknown",categoryPath:["Unknown"],categoryLabel:"Unknown",tags:[],nameId:null,nameStatus:"unassigned",nameSource:null,nameConfidence:0}))}
function projectPayload(){return{app:"Lineage Asset Studio",version:4,savedAt:new Date().toISOString(),categoryTree:CATEGORY_TREE,settings:settingsPayload(),namesCatalog:state.namesCatalog,referenceCatalog:state.referenceCatalog,backupState:{classificationsSinceBackup:state.classificationsSinceBackup,lastBackupAt:state.lastBackupAt?.toISOString()||null,projectDirty:state.projectDirty,dirtySince:state.dirtySince?.toISOString()||null},assets:Object.fromEntries(state.assets.map(a=>[a.uid,{category:a.category,categoryPath:a.categoryPath,categoryLabel:a.categoryLabel,tags:a.tags,nameId:a.nameId||null,nameStatus:a.nameStatus||"unassigned",nameSource:a.nameSource||null,nameConfidence:a.nameConfidence||0}]))}}
function categoryPathFromLabel(label){return String(label||"Unknown").split(" > ").map(x=>x.trim()).filter(Boolean)}
function categoryData(v,fallback="Unknown"){const label=String(v?.categoryLabel||v?.category||fallback),path=Array.isArray(v?.categoryPath)&&v.categoryPath.length?v.categoryPath.map(String):categoryPathFromLabel(label);return{label,path}}
function normalizeAssets(data){const list=Array.isArray(data)?data:data.assets;if(!Array.isArray(list))throw Error("assets_index.json 格式不正確");return list.map(a=>{const c=categoryData(a);return{...a,assetPrefix:a.assetPrefix||"",category:c.label,categoryLabel:c.label,categoryPath:c.path,tags:Array.isArray(a.tags)?a.tags:[],nameId:a.nameId||null,nameStatus:a.nameStatus||"unassigned",nameSource:a.nameSource||null,nameConfidence:Number(a.nameConfidence)||0}})}
function applyProject(p){if(validCategoryTree(p?.categoryTree)){CATEGORY_TREE=p.categoryTree;CATEGORIES=categoryTreeValues()}if(p?.namesCatalog?.names)state.namesCatalog=p.namesCatalog;if(Array.isArray(p?.referenceCatalog?.entries))state.referenceCatalog=p.referenceCatalog;if(p?.backupState){state.classificationsSinceBackup=Number(p.backupState.classificationsSinceBackup)||0;state.lastBackupAt=p.backupState.lastBackupAt?new Date(p.backupState.lastBackupAt):null;if(typeof p.backupState.projectDirty==="boolean"){state.projectDirty=p.backupState.projectDirty;state.dirtySince=p.backupState.dirtySince?new Date(p.backupState.dirtySince):null}}if(p?.backupState?.projectDirty===undefined){const saved=p?.savedAt?new Date(p.savedAt):null;if(saved&&!Number.isNaN(saved.getTime())&&(!state.lastBackupAt||saved>state.lastBackupAt)){state.projectDirty=true;state.dirtySince=saved}}const map=Array.isArray(p?.assets)?Object.fromEntries(p.assets.map(a=>[a.uid,a])):p?.assets||p?.classifications||{};state.assets.forEach(a=>{const v=map[a.uid];if(v){const c=categoryData(v,a.category);a.category=c.label;a.categoryLabel=c.label;a.categoryPath=c.path;a.tags=Array.isArray(v.tags)?[...new Set(v.tags.map(String))]:a.tags;a.nameId=v.nameId||null;a.nameStatus=v.nameStatus||"unassigned";a.nameSource=v.nameSource||null;a.nameConfidence=Number(v.nameConfidence)||0}});refreshNameSuggestions()}

function afterLoad(){buildGroups();refreshOptions();buildCategoryBrowser();refreshNameSuggestions();updateReferenceStatus();if(state.root)saveNameData().catch(e=>console.warn(e));state.page=1;applyFilters()}
function spriteRank(name){if(name==="Sprite")return-1;const m=name.match(/^Sprite(\d+)$/);return m?Number(m[1]):999}
function compareAssets(a,b){return(SOURCE_ORDER[a.sourceType]??99)-(SOURCE_ORDER[b.sourceType]??99)||spriteRank(a.spriteName)-spriteRank(b.spriteName)||a.originalNumber-b.originalNumber||(a.assetPrefix||"").localeCompare(b.assetPrefix||"")||(LANG_ORDER[a.lang]??99)-(LANG_ORDER[b.lang]??99)||a.fileName.localeCompare(b.fileName,undefined,{numeric:true})}
function compareCategoryAssets(a,b){return String(a.categoryLabel||a.category).localeCompare(String(b.categoryLabel||b.category),"zh-Hant")||compareAssets(a,b)}
function buildGroups(){const map=new Map;for(const a of [...state.assets].sort(compareAssets)){const key=`${a.sourceType}|${a.spriteName}|${a.assetPrefix||""}|${a.originalNumber}`;if(!map.has(key))map.set(key,{key,sourceType:a.sourceType,spriteName:a.spriteName,assetPrefix:a.assetPrefix||"",originalNumber:a.originalNumber,assets:[]});map.get(key).assets.push(a)}state.groups=[...map.values()].sort((a,b)=>(SOURCE_ORDER[a.sourceType]??99)-(SOURCE_ORDER[b.sourceType]??99)||spriteRank(a.spriteName)-spriteRank(b.spriteName)||a.originalNumber-b.originalNumber||a.assetPrefix.localeCompare(b.assetPrefix))}
function refreshOptions(){const sf=$("sourceFilter").value,sp=$("spriteFilter").value,cf=$("categoryFilter").value;fillSelect($("sourceFilter"),uniq(state.assets.map(a=>a.sourceType)));fillSelect($("spriteFilter"),uniq(state.assets.map(a=>a.spriteName),true));fillSelect($("categoryFilter"),uniq([...CATEGORIES,...state.assets.map(a=>a.categoryLabel||a.category)]));$("sourceFilter").value=sf;$("spriteFilter").value=sp;$("categoryFilter").value=cf}
function isUnknown(a){return String(a.categoryLabel||a.category||"Unknown").toLowerCase()==="unknown"}
function nameSearchText(a){const n=a.nameId?state.namesCatalog.names[a.nameId]:null;return n?normalizeName([n.label,...(n.aliases||[])].join(" ")):""}
function applyFilters(){const q=$("search").value.trim().toLowerCase(),src=$("sourceFilter").value,spr=$("spriteFilter").value,lang=$("langFilter").value,cat=$("categoryFilter").value,nameStatus=$("nameStatusFilter").value,nav=state.categoryNavFilter,rangeMin=state.serialRangeMin,rangeMax=state.serialRangeMax,nums=["minWidth","maxWidth","minHeight","maxHeight"].map(id=>Number($(id).value)||null),catalogUnknown=state.appMode==="catalog"&&state.catalogUnknownOnly,matches=a=>{const label=a.categoryLabel||a.category,named=!!resolvedName(a);return(rangeMin==null||a.originalNumber>=rangeMin)&&(rangeMax==null||a.originalNumber<=rangeMax)&&(!catalogUnknown||isUnknown(a))&&(!nameStatus||(nameStatus==="named"?named:!named))&&(!nav||label===nav||label.startsWith(nav+" > "))&&(!src||a.sourceType===src)&&(!spr||a.spriteName===spr)&&(!lang||a.lang===lang)&&(!cat||a.category===cat)&&(!nums[0]||a.width>=nums[0])&&(!nums[1]||a.width<=nums[1])&&(!nums[2]||a.height>=nums[2])&&(!nums[3]||a.height<=nums[3])&&(!q||a.fileName.toLowerCase().includes(q)||a.uid.toLowerCase().includes(q)||nameSearchText(a).includes(normalizeName(q)))};state.visibleAssets=state.assets.filter(matches).sort(state.viewMode==="category"?compareCategoryAssets:compareAssets);window.visibleAssets=state.visibleAssets;const visibleIds=new Set(state.visibleAssets.map(a=>a.uid));state.filtered=state.groups.filter(g=>g.assets.some(a=>visibleIds.has(a.uid)));$("quickSource").value=src;state.page=1;render()}
function clearFilters(){["search","sourceFilter","spriteFilter","langFilter","categoryFilter","nameStatusFilter","minWidth","maxWidth","minHeight","maxHeight","serialRangeStart","serialRangeEnd"].forEach(id=>$(id).value="");state.categoryNavFilter="";state.serialRangeMin=null;state.serialRangeMax=null;buildCategoryBrowser();applyFilters()}

function render(){clearURLs();const start=(state.page-1)*PAGE_SIZE,assetView=state.viewMode!=="source",allItems=assetView?state.visibleAssets:state.filtered,items=allItems.slice(start,start+PAGE_SIZE),totalAssets=state.visibleAssets.length;$("resultCount").textContent=assetView?`${totalAssets.toLocaleString()} 張圖片`:`${state.filtered.length.toLocaleString()} 個群組 / ${totalAssets.toLocaleString()} 張圖片`;$("gallery").replaceChildren(...items.map(assetView?assetCard:groupCard));$("emptyState").classList.toggle("hidden",state.assets.length>0);$("gallery").classList.toggle("hidden",state.assets.length===0);const pages=Math.max(1,Math.ceil(allItems.length/PAGE_SIZE));$("pagination").classList.toggle("hidden",allItems.length<=PAGE_SIZE);$("pageInfo").textContent=`第 ${state.page} / ${pages} 頁`;$("prevPage").disabled=state.page<=1;$("nextPage").disabled=state.page>=pages;const pageAssets=assetView?items:items.flatMap(g=>g.assets);$("selectPage").checked=pageAssets.length>0&&pageAssets.every(a=>state.selected.has(a.uid));$("selectPage").indeterminate=pageAssets.some(a=>state.selected.has(a.uid))&&!$("selectPage").checked;renderSectionInfo(items);updatePagination(pages);updateSelection()}
function assetCard(a){const card=el("article","card"+(state.selected.has(a.uid)?" selected":"")),thumb=el("div","thumb"),check=document.createElement("input"),badges=el("div","badge-row");card.dataset.key=a.uid;card.onmousedown=e=>{if(e.button===0){e.stopPropagation();selectAssetClick(a,e)}};card.ondblclick=()=>{const g=state.groups.find(x=>x.assets.some(v=>v.uid===a.uid));if(g)openGroup(g)};check.type="checkbox";check.className="pick";check.checked=state.selected.has(a.uid);check.tabIndex=-1;check.onclick=e=>e.preventDefault();thumb.append(check);loadAssetImage(a,thumb);badges.append(el("span","badge",a.lang));thumb.append(badges);card.append(nameInputForAsset(a),thumb);const info=el("div","card-info");info.append(el("div","card-title",a.fileName));const meta=el("div","meta");meta.append(el("span","",a.sourceType),el("span","",a.spriteName),el("span","",`#${a.originalNumber}`),el("span","",`${a.width}×${a.height}`),el("span","category",a.category));info.append(meta);card.append(info);return card}
function renderSectionInfo(items){const box=$("sectionInfo");box.classList.toggle("hidden",state.viewMode==="source"||!items.length);if(state.viewMode==="source"||!items.length)return;if(state.viewMode==="category"){const first=items[0],label=first.categoryLabel||first.category,same=items.filter(a=>(a.categoryLabel||a.category)===label);box.textContent=`分類：${label}｜本頁 ${same.length} 張`;return}const first=items[0],same=items.filter(a=>a.sourceType===first.sourceType&&a.spriteName===first.spriteName),min=Math.min(...same.map(a=>a.originalNumber)),max=Math.max(...same.map(a=>a.originalNumber));box.textContent=`${first.sourceType} / ${first.spriteName} / ${min} - ${max}`}
function groupCard(g){const selected=g.assets.filter(a=>state.selected.has(a.uid)).length,card=el("article","card"+(selected?" selected":"")),thumb=el("div","thumb"),check=document.createElement("input");card.dataset.key=g.key;card.onmousedown=e=>{if(e.button===0){e.stopPropagation();selectGroupClick(g,e)}};card.ondblclick=e=>{e.stopPropagation();openGroup(g)};check.type="checkbox";check.className="pick";check.checked=selected===g.assets.length;check.indeterminate=selected>0&&selected<g.assets.length;check.tabIndex=-1;check.onclick=e=>e.preventDefault();thumb.append(check);loadAssetImage(g.assets[0],thumb);const badges=el("div","badge-row");g.assets.forEach(a=>badges.append(el("span","badge",a.lang)));thumb.append(badges);const cats=uniq(g.assets.map(a=>a.categoryLabel||a.category)),names=uniq(g.assets.map(resolvedName).filter(Boolean)),categoryText=cats.length===1?cats[0]:"多種分類",nameText=names.length===1?names[0]:names.length?"多種名稱":"未命名";card.append(thumb);const info=el("div","card-info"),numberLabel=`${g.assetPrefix||""}${g.originalNumber}`;info.append(el("div","card-title",`${numberLabel} · ${categoryText}`),el("div","card-category",`${nameText} · ${g.spriteName}`));const meta=el("div","meta");meta.append(el("span","",g.sourceType),el("span","",`${g.assets.length} 個版本`));info.append(meta);card.append(info);return card}
async function loadAssetImage(asset,container){try{const h=await resolveFile(asset.relativePath),f=await h.getFile(),url=URL.createObjectURL(f),img=new Image();state.urls.push(url);img.loading="lazy";img.alt=asset.fileName;img.src=url;container.prepend(img)}catch{container.prepend(el("span","","無法載入"))}}
async function resolveFile(path){let h=state.root;const parts=path.split("/");for(let i=0;i<parts.length-1;i++)h=await h.getDirectoryHandle(parts[i]);return h.getFileHandle(parts.at(-1))}
function clearURLs(){state.urls.forEach(URL.revokeObjectURL);state.urls=[]}
function pageCount(){const total=state.viewMode!=="source"?state.visibleAssets.length:state.filtered.length;return Math.max(1,Math.ceil(total/PAGE_SIZE))}
function setPage(p){state.page=Math.max(1,Math.min(pageCount(),Number(p)||1));render();window.scrollTo({top:0,behavior:"smooth"})}
function jumpToPage(){setPage($("pageInput").value)}
function updatePagination(pages){for(const id of ["firstPage","topFirstPage"])$(id).disabled=state.page<=1;for(const id of ["lastPage","topLastPage"])$(id).disabled=state.page>=pages;for(const id of ["pageInput","topPageInput"]){$(id).max=pages;$(id).value=state.page}$("topPagination").classList.toggle("hidden",pages<=1);$("topPageInfo").textContent=`第 ${state.page} / ${pages} 頁`;$("topPrevPage").disabled=state.page<=1;$("topNextPage").disabled=state.page>=pages}
function togglePageSelection(e){currentPageAssets().forEach(a=>e.target.checked?state.selected.add(a.uid):state.selected.delete(a.uid));render()}

function pageGroups(){return state.filtered.slice((state.page-1)*PAGE_SIZE,state.page*PAGE_SIZE)}
function currentPageAssets(){return state.viewMode!=="source"?state.visibleAssets.slice((state.page-1)*PAGE_SIZE,state.page*PAGE_SIZE):pageGroups().flatMap(g=>g.assets)}
function setGroupSelected(g,on){g.assets.forEach(a=>on?state.selected.add(a.uid):state.selected.delete(a.uid))}
function selectGroupClick(g,e){
  const groups=pageGroups();
  if(e.shiftKey&&state.anchorKey){const a=groups.findIndex(x=>x.key===state.anchorKey),b=groups.findIndex(x=>x.key===g.key);if(a>=0&&b>=0){if(!e.ctrlKey)state.selected.clear();for(let i=Math.min(a,b);i<=Math.max(a,b);i++)setGroupSelected(groups[i],true)}}
  else{const was=g.assets.every(a=>state.selected.has(a.uid));if(!e.ctrlKey)state.selected.clear();setGroupSelected(g,e.ctrlKey?!was:true);state.anchorKey=g.key}
  render();
}
function selectAssetClick(a,e){if(e.shiftKey&&state.anchorKey){const start=state.visibleAssets.findIndex(x=>x.uid===state.anchorKey),end=state.visibleAssets.findIndex(x=>x.uid===a.uid);if(start>=0&&end>=0){if(!e.ctrlKey)state.selected.clear();for(let i=Math.min(start,end);i<=Math.max(start,end);i++)state.selected.add(state.visibleAssets[i].uid)}}else{const was=state.selected.has(a.uid);if(!e.ctrlKey)state.selected.clear();if(!e.ctrlKey||!was)state.selected.add(a.uid);state.anchorKey=a.uid}render()}
function setViewMode(mode){state.viewMode=mode;state.page=1;state.anchorKey=null;$("sourceView").classList.toggle("active",mode==="source");$("serialView").classList.toggle("active",mode==="serial");$("categoryView").classList.toggle("active",mode==="category");state.visibleAssets.sort(mode==="category"?compareCategoryAssets:compareAssets);window.visibleAssets=state.visibleAssets;render()}
function jumpToSprite(name){if(!name){state.page=1;render();return}const list=state.viewMode!=="source"?state.visibleAssets:state.filtered,index=list.findIndex(x=>x.spriteName===name);if(index<0)return showNotice(`目前篩選結果中沒有 ${name}。`,true);state.page=Math.floor(index/PAGE_SIZE)+1;render();window.scrollTo({top:0,behavior:"smooth"})}
function setAppMode(mode){state.appMode=mode;state.page=1;state.anchorKey=null;state.selected.clear();const catalog=mode==="catalog";if(catalog){state.catalogUnknownOnly=false;state.categoryNavFilter="";$("categoryFilter").value="";setViewMode("serial")}$("normalMode").classList.toggle("active",!catalog);$("catalogMode").classList.toggle("active",catalog);$("catalogSidebar").classList.toggle("hidden",!catalog);$("catalogTools").classList.toggle("hidden",!catalog);$("catalogInspector").classList.toggle("hidden",!catalog);$("catalogStatus").classList.toggle("hidden",!catalog);$("normalCategoryPanel").classList.toggle("hidden",catalog);$("batchPanel").classList.toggle("hidden",catalog);$("topToggleClassified").classList.toggle("hidden",!catalog);document.querySelector("main.layout").classList.toggle("catalog-mode",catalog);syncClassifiedToggle();buildCategoryBrowser();applyFilters()}
function syncClassifiedToggle(){$("toggleUnknown").textContent=state.catalogUnknownOnly?"顯示全部素材":"只顯示 Unknown";$("topToggleClassified").textContent=state.catalogUnknownOnly?"顯示已分類":"隱藏已分類";$("topToggleClassified").classList.toggle("active",state.catalogUnknownOnly)}
function toggleCatalogUnknown(){state.catalogUnknownOnly=!state.catalogUnknownOnly;if(state.catalogUnknownOnly){state.categoryNavFilter="";$("categoryFilter").value=""}syncClassifiedToggle();buildCategoryBrowser();applyFilters()}
function applySerialRangeFilter(){const start=$("serialRangeStart").value.trim(),end=$("serialRangeEnd").value.trim();if(!start&&!end)return showNotice("請輸入起始或結束流水號。",true);let min=start===""?null:Number(start),max=end===""?null:Number(end);if((min!=null&&!Number.isFinite(min))||(max!=null&&!Number.isFinite(max)))return showNotice("流水號必須是數字。",true);if(min!=null&&max!=null&&min>max)[min,max]=[max,min];state.serialRangeMin=min;state.serialRangeMax=max;$("serialRangeStart").value=min??"";$("serialRangeEnd").value=max??"";applyFilters();showNotice(`目前顯示流水號 ${min??"最小"} 到 ${max??"最大"}，共 ${state.visibleAssets.length.toLocaleString()} 張素材。`)}
function clearSerialRangeFilter(){state.serialRangeMin=null;state.serialRangeMax=null;$("serialRangeStart").value="";$("serialRangeEnd").value="";applyFilters();showNotice("流水號區間已清除。")}
function jumpUnknown(direction){const list=state.visibleAssets.filter(isUnknown);if(!list.length)return showNotice("目前篩選條件中沒有 Unknown 素材。",true);let index=list.findIndex(a=>state.selected.has(a.uid));if(index<0){const pageStart=(state.page-1)*PAGE_SIZE,indexInAll=Math.min(pageStart,state.visibleAssets.length-1),current=state.visibleAssets[indexInAll];index=Math.max(0,list.findIndex(a=>a.uid===current?.uid))}index=Math.max(0,Math.min(list.length-1,index+direction));const target=list[index],visibleIndex=state.visibleAssets.findIndex(a=>a.uid===target.uid);state.page=Math.floor(visibleIndex/PAGE_SIZE)+1;render();focusVisibleAsset(target.uid)}
function focusVisibleAsset(uid){if(!uid)return;requestAnimationFrame(()=>{const card=[...document.querySelectorAll("#gallery .card")].find(x=>x.dataset.key===uid);if(card){card.scrollIntoView({block:"center",behavior:"smooth"});card.classList.add("catalog-focus");setTimeout(()=>card.classList.remove("catalog-focus"),1300)}})}
function startBandSelection(e){
  if(e.button!==0||e.target.closest(".card"))return;
  e.preventDefault();hideContextMenu();const base=e.ctrlKey?new Set(state.selected):new Set();if(!e.ctrlKey)state.selected.clear();
  state.drag={x:e.clientX,y:e.clientY,base};const band=$("selectionBand");band.classList.remove("hidden");
  const move=ev=>{const x=Math.min(state.drag.x,ev.clientX),y=Math.min(state.drag.y,ev.clientY),w=Math.abs(ev.clientX-state.drag.x),h=Math.abs(ev.clientY-state.drag.y),box={left:x,top:y,right:x+w,bottom:y+h};Object.assign(band.style,{left:`${x}px`,top:`${y}px`,width:`${w}px`,height:`${h}px`});state.selected=new Set(state.drag.base);document.querySelectorAll("#gallery .card").forEach(card=>{const r=card.getBoundingClientRect(),hit=r.left<box.right&&r.right>box.left&&r.top<box.bottom&&r.bottom>box.top;if(state.viewMode!=="source"){const a=currentPageAssets().find(v=>v.uid===card.dataset.key);if(hit&&a)state.selected.add(a.uid);card.classList.toggle("selected",!!a&&state.selected.has(a.uid))}else{const g=pageGroups().find(v=>v.key===card.dataset.key);if(hit&&g)setGroupSelected(g,true);card.classList.toggle("selected",!!g&&g.assets.some(a=>state.selected.has(a.uid)))}});updateSelection()};
  const up=()=>{document.removeEventListener("mousemove",move);document.removeEventListener("mouseup",up);band.classList.add("hidden");state.drag=null;render()};document.addEventListener("mousemove",move);document.addEventListener("mouseup",up);
}

function openContextMenu(e){e.preventDefault();const card=e.target.closest(".card");if(card){if(state.viewMode!=="source"){const a=currentPageAssets().find(x=>x.uid===card.dataset.key);if(a&&!state.selected.has(a.uid)){state.selected.clear();state.selected.add(a.uid);state.anchorKey=a.uid;render()}}else{const g=pageGroups().find(x=>x.key===card.dataset.key);if(g&&!g.assets.some(a=>state.selected.has(a.uid))){state.selected.clear();setGroupSelected(g,true);state.anchorKey=g.key;render()}}}if(!state.selected.size)return;const menu=$("contextMenu");menu.style.left=`${Math.min(e.clientX,innerWidth-180)}px`;menu.style.top=`${Math.min(e.clientY,innerHeight-220)}px`;menu.classList.remove("hidden")}
function hideContextMenu(){$("contextMenu").classList.add("hidden")}
function handleContextAction(e){const action=e.target.dataset.action;if(!action)return;hideContextMenu();if(action==="category")$("categoryDialog").showModal();if(action==="tag"){$("dialogTagInput").value="";$("tagDialog").showModal()}if(action==="clear-category")applyCategoryValue("Unknown");if(action==="clear-tags")clearSelectedTags();if(action==="info")showSelectedInfo();if(action==="export-selected")openSelectedMediaExport()}
function buildLegacyCategoryTree(){
  const makeButton=(parent,child,catalog=false)=>{const value=child?`${parent} > ${child}`:parent,b=el("button",catalog?`category-choice${state.currentCategory===value?" active":""}`:"",child||parent);b.onclick=()=>{state.currentCategory=value;if(catalog){document.querySelectorAll("#catalogCategoryTree .category-choice.active").forEach(x=>x.classList.remove("active"));b.classList.add("active")}updateSelection();if(state.selected.size)applyCategoryValue(value);if(!catalog)$("categoryDialog").close()};return b},action=(text,title,disabled,handler)=>{const b=el("button","tree-action",text);b.title=title;b.disabled=disabled;b.onclick=e=>{e.preventDefault();e.stopPropagation();handler()};return b},root=$("categoryTree"),entries=Object.entries(CATEGORY_TREE);
  root.replaceChildren(...entries.map(([parent,children])=>{const box=el("section","category-branch"),title=el("h3","",parent);box.append(title);(children.length?children:[""]).forEach(child=>box.append(makeButton(parent,child)));return box}));
  $("catalogCategoryTree").replaceChildren(...entries.map(([parent,children],parentIndex)=>{const details=document.createElement("details"),summary=document.createElement("summary"),label=el("span","category-heading",parent),actions=el("span","tree-actions");actions.append(action("上移","主分類上移",parentIndex===0,()=>moveCategory(parent,null,-1)),action("下移","主分類下移",parentIndex===entries.length-1,()=>moveCategory(parent,null,1)));if(parent!=="Unknown"){actions.append(action("新增","新增子分類",false,()=>openCategoryEditor({mode:"add-child",parent})),action("改名","重新命名主分類",false,()=>openCategoryEditor({mode:"rename-root",parent})));const remove=action("刪除","刪除主分類",false,()=>deleteCategory(parent,null));remove.classList.add("danger");actions.append(remove)}summary.append(label,actions);details.open=parent!=="Unknown";details.append(summary);if(children.length)children.forEach((child,childIndex)=>{const row=el("div","tree-leaf"),childActions=el("span","tree-actions");row.append(makeButton(parent,child,true));childActions.append(action("上移","子分類上移",childIndex===0,()=>moveCategory(parent,child,-1)),action("下移","子分類下移",childIndex===children.length-1,()=>moveCategory(parent,child,1)),action("改名","重新命名子分類",false,()=>openCategoryEditor({mode:"rename-child",parent,child})));const remove=action("刪除","刪除子分類",false,()=>deleteCategory(parent,child));remove.classList.add("danger");childActions.append(remove);row.append(childActions);details.append(row)});else details.append(makeButton(parent,"",true));return details}))
}
async function moveCategory(parent,child,delta){if(child==null){const entries=Object.entries(CATEGORY_TREE),index=entries.findIndex(([key])=>key===parent),target=index+delta;if(index<0||target<0||target>=entries.length)return;[entries[index],entries[target]]=[entries[target],entries[index]];CATEGORY_TREE=Object.fromEntries(entries)}else{const children=CATEGORY_TREE[parent],index=children.indexOf(child),target=index+delta;if(index<0||target<0||target>=children.length)return;[children[index],children[target]]=[children[target],children[index]]}CATEGORIES=categoryTreeValues();buildCategoryTree();refreshCategoryControls();await Promise.all([saveSettings(),saveProject()]);showNotice("分類順序已更新。")}
async function deleteCategory(parent,child){if(parent==="Unknown")return;const path=child?`${parent} > ${child}`:parent,affected=state.assets.filter(a=>{const label=a.categoryLabel||a.category;return child?label===path:label===parent||label.startsWith(parent+" > ")});if(!confirm(`確定刪除「${path}」？${affected.length?`\n其中 ${affected.length} 張素材會移回 Unknown。`:""}`))return;await createSnapshot("刪除分類前");if(child)CATEGORY_TREE[parent]=CATEGORY_TREE[parent].filter(x=>x!==child);else delete CATEGORY_TREE[parent];affected.forEach(a=>{a.category="Unknown";a.categoryLabel="Unknown";a.categoryPath=["Unknown"]});if(state.categoryNavFilter===path||(!child&&state.categoryNavFilter.startsWith(parent+" > ")))state.categoryNavFilter="";state.undo=[];state.redo=[];CATEGORIES=categoryTreeValues();buildCategoryTree();refreshCategoryControls();state.projectDirty=true;state.dirtySince=state.dirtySince||new Date();applyFilters();await Promise.all([saveSettings(),saveProject()]);showNotice(`分類「${path}」已刪除${affected.length?`，${affected.length} 張素材已移回 Unknown`:""}。`)}

const TREE_ICONS={UI:"M4 5h16v11H4zM8 20h8",Item:"M5 7l7-4 7 4v10l-7 4-7-4z",Character:"M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm-7 9c0-4 3-7 7-7s7 3 7 7",Effect:"M13 2 5 14h6l-1 8 9-13h-6z",Map:"M3 6l6-3 6 3 6-3v15l-6 3-6-3-6 3zM9 3v15m6-12v15",Unknown:"M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20zm0-6v.01M9.7 9a2.4 2.4 0 1 1 3.5 2.1c-.8.4-1.2.9-1.2 1.9"};
function treeIcon(name){const span=el("span","tree-icon");span.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${TREE_ICONS[name]||"M4 5h16v14H4zM4 9h16"}"/></svg>`;return span}
function categoryCount(path){return state.assets.reduce((n,a)=>{const label=a.categoryLabel||a.category;return n+(label===path||label.startsWith(path+" > ")?1:0)},0)}
function selectTreeCategory(value,row){state.currentCategory=value;document.querySelectorAll("#catalogCategoryTree .tree-row.selected").forEach(x=>x.classList.remove("selected"));row.classList.add("selected");updateSelection();if(state.selected.size)applyCategoryValue(value)}
function treeDnD(node,parent,child){node.draggable=parent!=="Unknown";node.dataset.parent=parent;node.dataset.child=child||"";node.ondragstart=e=>{e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("text/plain",JSON.stringify({parent,child:child||null}));node.classList.add("dragging")};node.ondragend=()=>node.classList.remove("dragging");node.ondragover=e=>{e.preventDefault();node.classList.add("drag-over")};node.ondragleave=()=>node.classList.remove("drag-over");node.ondrop=e=>{e.preventDefault();e.stopPropagation();node.classList.remove("drag-over");try{moveTreeNode(JSON.parse(e.dataTransfer.getData("text/plain")),{parent,child:child||null})}catch{}}}
function buildCategoryTree(){const dialogRoot=$("categoryTree"),catalogRoot=$("catalogCategoryTree"),query=normalizeName($("categoryTreeSearch")?.value||"");if(dialogRoot){const make=(parent,child)=>{const value=child?`${parent} > ${child}`:parent,b=el("button","",child||parent);b.onclick=()=>{state.currentCategory=value;updateSelection();if(state.selected.size)applyCategoryValue(value);$("categoryDialog").close()};return b};dialogRoot.replaceChildren(...Object.entries(CATEGORY_TREE).map(([parent,children])=>{const box=el("section","category-branch");box.append(el("h3","",parent));(children.length?children:[""]).forEach(child=>box.append(make(parent,child)));return box}))}if(!catalogRoot)return;const nodes=[];for(const [parent,children]of Object.entries(CATEGORY_TREE)){const matches=children.filter(c=>!query||normalizeName(c).includes(query)),show=!query||normalizeName(parent).includes(query)||matches.length;if(!show)continue;const visibleChildren=query&&!normalizeName(parent).includes(query)?matches:children,details=document.createElement("details"),summary=document.createElement("summary"),rootRow=el("div",`tree-row tree-root${state.currentCategory===parent?" selected":""}`),name=el("span","tree-name",parent),count=el("span","tree-count",categoryCount(parent).toLocaleString());rootRow.append(treeIcon(parent),name,count);rootRow.onclick=e=>{e.preventDefault();e.stopPropagation();selectTreeCategory(parent,rootRow)};rootRow.oncontextmenu=e=>openTreeContextMenu(e,parent,null);treeDnD(summary,parent,null);summary.append(rootRow);details.open=!!query||state.currentCategory===parent||state.currentCategory.startsWith(parent+" > ");details.append(summary);const branch=el("div","tree-children");for(const child of visibleChildren){const value=`${parent} > ${child}`,row=el("div",`tree-row tree-child${state.currentCategory===value?" selected":""}`);row.append(el("span","tree-indent"),el("span","tree-name",child),el("span","tree-count",categoryCount(value).toLocaleString()));row.onclick=()=>selectTreeCategory(value,row);row.oncontextmenu=e=>openTreeContextMenu(e,parent,child);treeDnD(row,parent,child);branch.append(row)}details.append(branch);nodes.push(details)}catalogRoot.replaceChildren(...nodes,...(nodes.length?[]:[el("div","tree-empty","找不到符合的分類")]))}
const buildCategoryTreeCore=buildCategoryTree;
buildCategoryTree=function(){const page=state.page;buildCategoryTreeCore();if(page>1){const token={};state.categoryTreePageRestoreToken=token;queueMicrotask(()=>{if(state.categoryTreePageRestoreToken!==token||state.page!==1)return;state.page=Math.min(page,pageCount());render()})}};
function openTreeContextMenu(e,parent,child){e.preventDefault();e.stopPropagation();state.treeContext={parent,child};const menu=$("categoryContextMenu"),locked=parent==="Unknown";menu.querySelector('[data-tree-action="add"]').textContent=child?"新增同層分類":"新增子分類";for(const action of ["rename","delete","up","down"])menu.querySelector(`[data-tree-action="${action}"]`).disabled=locked;menu.style.left=`${Math.min(e.clientX,innerWidth-190)}px`;menu.style.top=`${Math.min(e.clientY,innerHeight-210)}px`;menu.classList.remove("hidden")}
function hideTreeContextMenu(){$("categoryContextMenu")?.classList.add("hidden")}
function handleTreeContextAction(e){const action=e.target.dataset.treeAction,cfg=state.treeContext;if(!action||!cfg)return;hideTreeContextMenu();if(action==="add")openCategoryEditor({mode:"add-child",parent:cfg.parent});if(action==="rename")openCategoryEditor({mode:cfg.child?"rename-child":"rename-root",parent:cfg.parent,child:cfg.child});if(action==="delete")deleteCategory(cfg.parent,cfg.child);if(action==="up")moveCategory(cfg.parent,cfg.child,-1);if(action==="down")moveCategory(cfg.parent,cfg.child,1)}
async function moveCategoryViaMenu({parent,child}){if(child){const choices=Object.keys(CATEGORY_TREE).filter(x=>x!=="Unknown"&&x!==parent),target=prompt(`移動「${child}」到哪個主分類？\n${choices.join("、")}`,choices[0]||"");if(target&&CATEGORY_TREE[target])await moveTreeNode({parent,child},{parent:target,child:null})}else{const order=Object.keys(CATEGORY_TREE),position=Number(prompt(`將「${parent}」移到第幾位？（1-${order.length}）`,String(order.indexOf(parent)+1)));if(Number.isFinite(position))await reorderRoot(parent,Math.max(0,Math.min(order.length-1,position-1)))}}
async function reorderRoot(parent,targetIndex){const entries=Object.entries(CATEGORY_TREE),index=entries.findIndex(([p])=>p===parent);if(index<0||parent==="Unknown")return;const [item]=entries.splice(index,1);entries.splice(targetIndex,0,item);CATEGORY_TREE=Object.fromEntries(entries);await persistTreeOrder()}
async function moveTreeNode(from,to){if(!from?.parent||from.parent==="Unknown")return;if(!from.child){const target=Object.keys(CATEGORY_TREE).indexOf(to.parent);return reorderRoot(from.parent,target)}const source=CATEGORY_TREE[from.parent],oldIndex=source.indexOf(from.child);if(oldIndex<0||to.parent==="Unknown")return;source.splice(oldIndex,1);const target=CATEGORY_TREE[to.parent];let insert=to.child?target.indexOf(to.child):target.length;if(from.parent===to.parent&&oldIndex<insert)insert--;target.splice(Math.max(0,insert),0,from.child);if(from.parent!==to.parent)migrateCategoryLabels(`${from.parent} > ${from.child}`,`${to.parent} > ${from.child}`,false);await persistTreeOrder()}
async function persistTreeOrder(){CATEGORIES=categoryTreeValues();state.undo=[];state.redo=[];buildCategoryTree();refreshCategoryControls();applyFilters();await Promise.all([saveSettings(),saveProject()]);showNotice("分類樹順序已更新。")}
function startSidebarResize(e){if(state.appMode!=="catalog")return;e.preventDefault();document.body.classList.add("resizing-sidebar");const move=ev=>{const width=Math.max(220,Math.min(480,ev.clientX));document.documentElement.style.setProperty("--sidebar-width",`${width}px`);localStorage.setItem("lineageCatalogSidebarWidth",String(width))},up=()=>{document.removeEventListener("mousemove",move);document.removeEventListener("mouseup",up);document.body.classList.remove("resizing-sidebar")};document.addEventListener("mousemove",move);document.addEventListener("mouseup",up)}
function startRightPanelResize(e){if(state.appMode!=="catalog")return;e.preventDefault();document.body.classList.add("resizing-sidebar");const move=ev=>{const width=Math.max(260,Math.min(520,innerWidth-ev.clientX));document.documentElement.style.setProperty("--inspector-width",`${width}px`);localStorage.setItem("lineageInspectorWidth",String(width))},up=()=>{document.removeEventListener("mousemove",move);document.removeEventListener("mouseup",up);document.body.classList.remove("resizing-sidebar")};document.addEventListener("mousemove",move);document.addEventListener("mouseup",up)}

function buildCategoryBrowser(){const root=$("categoryBrowser");if(!root)return;const countFor=path=>state.assets.filter(a=>{const label=a.categoryLabel||a.category;return label===path||label.startsWith(path+" > ")}).length,button=(label,path,cls="")=>{const b=el("button",cls+(state.categoryNavFilter===path?" active":""));b.append(el("span","",label),el("small","",countFor(path).toLocaleString()));b.onclick=()=>setCategoryNav(path);return b},all=el("button","category-all"+(state.categoryNavFilter===""?" active":""));all.append(el("span","","全部分類"),el("small","",state.assets.length.toLocaleString()));all.onclick=()=>setCategoryNav("");root.replaceChildren(all,...Object.entries(CATEGORY_TREE).map(([parent,children])=>{const details=document.createElement("details"),summary=document.createElement("summary");summary.append(el("span","",parent),el("small","",countFor(parent).toLocaleString()));details.open=state.categoryNavFilter===parent||state.categoryNavFilter.startsWith(parent+" > ");details.append(summary,button(`全部 ${parent}`,parent));children.forEach(child=>details.append(button(child,`${parent} > ${child}`)));return details}))}
function setCategoryNav(path){state.categoryNavFilter=path;buildCategoryBrowser();if(state.viewMode!=="category")setViewMode("category");applyFilters()}

function categoryTreeValues(){return Object.entries(CATEGORY_TREE).flatMap(([parent,children])=>children.length?children.map(child=>`${parent} > ${child}`):[parent])}
function validCategoryTree(tree){return!!tree&&typeof tree==="object"&&!Array.isArray(tree)&&Object.prototype.hasOwnProperty.call(tree,"Unknown")&&Object.entries(tree).every(([k,v])=>k&&Array.isArray(v)&&v.every(x=>typeof x==="string"&&x))}
function openCategoryEditor(config){state.categoryEditor=config;const rename=config.mode.startsWith("rename");$("categoryEditorTitle").textContent=rename?"重新命名分類":config.mode==="add-root"?"新增主分類":"新增子分類";$("categoryParentField").classList.toggle("hidden",config.mode!=="add-child");fillSelect($("categoryParent"),Object.keys(CATEGORY_TREE).filter(x=>x!=="Unknown"),false);if(config.parent)$("categoryParent").value=config.parent;$("categoryName").value=config.child||config.parent||"";$("categoryEditorDialog").showModal();$("categoryName").focus()}
async function saveCategoryEditor(){const cfg=state.categoryEditor,name=$("categoryName").value.trim();if(!cfg||!name||name.includes(">"))return showNotice("分類名稱不可空白，也不能包含 >。",true);if(cfg.mode==="add-root"){if(Object.prototype.hasOwnProperty.call(CATEGORY_TREE,name))return showNotice("已有同名主分類。",true);CATEGORY_TREE[name]=[]}else if(cfg.mode==="add-child"){const parent=$("categoryParent").value;if(!parent||CATEGORY_TREE[parent].includes(name))return showNotice("請選擇上層分類，且名稱不可重複。",true);CATEGORY_TREE[parent].push(name)}else if(cfg.mode==="rename-root"){if(cfg.parent==="Unknown")return;if(name!==cfg.parent&&Object.prototype.hasOwnProperty.call(CATEGORY_TREE,name))return showNotice("已有同名主分類。",true);const next={};for(const [key,value]of Object.entries(CATEGORY_TREE))next[key===cfg.parent?name:key]=value;CATEGORY_TREE=next;migrateCategoryLabels(cfg.parent,name,true)}else if(cfg.mode==="rename-child"){if(name!==cfg.child&&CATEGORY_TREE[cfg.parent].includes(name))return showNotice("此主分類下已有同名分類。",true);CATEGORY_TREE[cfg.parent]=CATEGORY_TREE[cfg.parent].map(x=>x===cfg.child?name:x);migrateCategoryLabels(`${cfg.parent} > ${cfg.child}`,`${cfg.parent} > ${name}`,false)}state.undo=[];state.redo=[];CATEGORIES=categoryTreeValues();buildCategoryTree();refreshCategoryControls();$("categoryEditorDialog").close();applyFilters();await Promise.all([saveSettings(),saveProject()]);showNotice("分類樹已更新並儲存。")}
function migrateCategoryLabels(from,to,includeChildren){state.assets.forEach(a=>{const label=a.categoryLabel||a.category;if(label===from||(includeChildren&&label.startsWith(from+" > "))){const next=to+label.slice(from.length);a.category=next;a.categoryLabel=next;a.categoryPath=categoryPathFromLabel(next)}})}
function refreshCategoryControls(){const batch=$("batchCategory").value,filter=$("categoryFilter").value;fillSelect($("batchCategory"),CATEGORIES,false);fillSelect($("categoryFilter"),uniq([...CATEGORIES,...state.assets.map(a=>a.categoryLabel||a.category)]));if(CATEGORIES.includes(batch))$("batchCategory").value=batch;if([...$("categoryFilter").options].some(o=>o.value===filter))$("categoryFilter").value=filter;buildCategoryBrowser()}
async function saveSettings(){if(!state.root)return;if(!state.projectDirty)state.dirtySince=new Date();state.projectDirty=true;try{const d=await state.root.getDirectoryHandle(".LineageAssetStudio",{create:true});await writeJSON(d,"settings.json",settingsPayload())}catch(e){showNotice(`分類樹設定儲存失敗：${e.message}`,true)}}
function handleKeyboard(e){if(e.target.matches("input,textarea,select")||document.querySelector("dialog[open]"))return;const ctrl=e.ctrlKey||e.metaKey;if(ctrl&&e.key.toLowerCase()==="a"){e.preventDefault();currentPageAssets().forEach(a=>state.selected.add(a.uid));render()}else if(e.key==="Escape"){state.selected.clear();render()}else if(e.key==="Delete"){e.preventDefault();applyCategoryValue("Unknown")}else if(ctrl&&e.key.toLowerCase()==="z"){e.preventDefault();undoCategory()}else if(ctrl&&e.key.toLowerCase()==="y"){e.preventDefault();redoCategory()}else if(e.key.toLowerCase()==="f"&&state.appMode==="catalog"){e.preventDefault();toggleCatalogUnknown()}else if(e.key==="Enter"&&state.selected.size){e.preventDefault();applyCategoryValue(state.currentCategory)}}
function clearSelectedTags(){const list=selectedAssets();if(!list.length)return;list.forEach(a=>a.tags=[]);changed(`${list.length} 張圖片的 Tag 已清除。`)}
function confirmDialogTags(){const tags=$("dialogTagInput").value.split(/[,，]/).map(s=>s.trim()).filter(Boolean);if(!tags.length)return;const list=selectedAssets();list.forEach(a=>a.tags=[...new Set([...a.tags,...tags])]);$("tagDialog").close();changed(`${list.length} 張圖片已加入 Tag。`)}
function showSelectedInfo(){const list=selectedAssets();$("infoSummary").textContent=`共 ${list.length.toLocaleString()} 張圖片`;$("infoContent").textContent=list.slice(0,500).map(a=>`${a.uid}\n  ${a.relativePath}\n  ${a.width}×${a.height}｜${a.category}｜${a.tags.join(", ")||"無 Tag"}`).join("\n\n")+(list.length>500?`\n\n…另有 ${list.length-500} 張未顯示`:"");$("infoDialog").showModal()}

function openGroup(g){clearURLs();$("dialogTitle").textContent=`${g.sourceType} / ${g.spriteName} / ${g.assetPrefix||""}${g.originalNumber}`;$("dialogMeta").textContent=`${g.assets.length} 個語言版本`;$("versionGrid").replaceChildren(...g.assets.map(a=>{const v=el("article","version"),t=el("div","thumb");loadAssetImage(a,t);const f=document.createElement("footer"),lab=document.createElement("label"),c=document.createElement("input");c.type="checkbox";c.checked=state.selected.has(a.uid);c.onchange=()=>{c.checked?state.selected.add(a.uid):state.selected.delete(a.uid);updateSelection()};lab.append(c,document.createTextNode(`${a.lang} · ${a.fileName}`));f.append(lab,el("p","",`${a.width} × ${a.height} · ${a.category}`),el("p","",a.tags.length?`# ${a.tags.join("  # ")}`:"尚無 tags"));v.append(t,f);return v}));$("groupDialog").showModal()}
function closeDialog(){$("groupDialog").close();render()}
function updateSelection(){const count=state.selected.size;$("selectionCount").textContent=`已選 ${count.toLocaleString()} 張圖片`;$("hudCount").textContent=`${count.toLocaleString()} 張`;$("hudCategory").textContent=state.currentCategory;$("selectionHud").classList.toggle("hidden",!count);updateCatalogStatus();updateCatalogInspector();renderNameReferenceList()}
function updateCatalogStatus(){if(state.appMode!=="catalog")return;const unknown=state.assets.filter(isUnknown).length;$("statusTotal").textContent=state.assets.length.toLocaleString();$("statusClassified").textContent=(state.assets.length-unknown).toLocaleString();$("statusUnknown").textContent=unknown.toLocaleString();$("statusSelected").textContent=state.selected.size.toLocaleString();$("statusSession").textContent=state.sessionClassified.toLocaleString()}
function updateCatalogInspector(){if(state.appMode!=="catalog")return;const list=selectedAssets();if(!list.length){$("catalogSelectionInfo").textContent="尚未選取素材";$("assetNameInput").value="";$("assetNameMeta").textContent="";$("nameClassEditor").disabled=true;return}const first=list[0],names=[...new Set(list.map(resolvedName).filter(Boolean))],record=first.nameId?state.namesCatalog.names[first.nameId]:null;$("catalogSelectionInfo").textContent=[`已選取：${list.length} 張`,`UID：${first.uid}`,`檔名：${first.fileName}`,`來源：${first.sourceType} / ${first.spriteName}`,`流水號：${first.originalNumber}`,`語言：${first.lang}`,`尺寸：${first.width} × ${first.height}`,`分類：${first.categoryLabel||first.category}`,`名稱：${names.length===1?names[0]:names.length?"多種名稱":"未命名"}`,`Tags：${first.tags.join(", ")||"無"}`,list.length>1?`\n另有 ${list.length-1} 張已選素材`:""].join("\n");$("assetNameInput").value=names.length===1?names[0]:"";$("nameClassEditor").disabled=!record;if(record)$("nameClassEditor").value=`${record.type||"other"}:${record.subtype||"other"}`;$("assetNameMeta").textContent=record?`nameId: ${record.nameId}｜分類：${nameTypeLabel(record.type||"other",record.subtype||"other")}｜來源：${record.source}｜別名：${(record.aliases||[]).join("、")||"無"}`:"輸入名稱後可套用到所有已選素材。"}
function selectedAssets(){return state.assets.filter(a=>state.selected.has(a.uid))}
function applyCategory(){applyCategoryValue($("batchCategory").value)}
function applyCategoryValue(value,record=true){const list=selectedAssets();if(!list.length)return showNotice("請先選取圖片。",true);const oldIndex=Math.max(0,state.visibleAssets.findIndex(a=>state.selected.has(a.uid))),changes=list.filter(a=>(a.categoryLabel||a.category)!==value).map(a=>({uid:a.uid,before:a.categoryLabel||a.category,after:value}));if(!changes.length)return;if(record){state.undo.push(changes);state.redo=[];state.classificationsSinceBackup++}const map=new Map(changes.map(x=>[x.uid,x.after]));state.assets.forEach(a=>{if(map.has(a.uid)){const label=map.get(a.uid);a.category=label;a.categoryLabel=label;a.categoryPath=categoryPathFromLabel(label)}});if(!isUnknown({categoryLabel:value}))state.sessionClassified+=changes.filter(x=>String(x.before).toLowerCase()==="unknown").length;state.currentCategory=value;changed(`${changes.length} 張圖片已套用分類「${value}」。`);if(state.classificationsSinceBackup>=100)createSnapshot("100 次批次分類");if(state.appMode==="catalog"&&!isUnknown({categoryLabel:value})){state.selected.clear();const next=Math.min(oldIndex,Math.max(0,state.visibleAssets.length-1));state.page=Math.floor(next/PAGE_SIZE)+1;render();focusVisibleAsset(state.visibleAssets[next]?.uid)}}
function applyHistory(changes,direction){const map=new Map(changes.map(x=>[x.uid,x[direction]]));state.assets.forEach(a=>{if(map.has(a.uid)){const label=map.get(a.uid);a.category=label;a.categoryLabel=label;a.categoryPath=categoryPathFromLabel(label)}});const delta=changes.reduce((n,x)=>n+(direction==="before"?(String(x.after).toLowerCase()!=="unknown"&&String(x.before).toLowerCase()==="unknown"?-1:0):(String(x.before).toLowerCase()==="unknown"&&String(x.after).toLowerCase()!=="unknown"?1:0)),0);state.sessionClassified=Math.max(0,state.sessionClassified+delta);state.currentCategory=changes.at(-1)?.[direction]||"Unknown";changed(direction==="before"?"已復原上一個分類操作。":"已重做分類操作。")}
function undoCategory(){const changes=state.undo.pop();if(!changes)return;state.redo.push(changes);applyHistory(changes,"before")}
function redoCategory(){const changes=state.redo.pop();if(!changes)return;state.undo.push(changes);applyHistory(changes,"after")}
function addTags(){const tags=$("tagInput").value.split(/[,，]/).map(s=>s.trim()).filter(Boolean),list=selectedAssets();if(!list.length)return showNotice("請先選取圖片。",true);if(!tags.length)return showNotice("請輸入至少一個 tag。",true);list.forEach(a=>a.tags=[...new Set([...a.tags,...tags])]);$("tagInput").value="";changed(`${list.length} 張圖片已加入 tag。`)}
function changed(msg){if(!state.projectDirty)state.dirtySince=new Date();state.projectDirty=true;const page=state.page;buildGroups();buildCategoryBrowser();applyFilters();state.page=Math.min(page,pageCount());render();showNotice(msg);clearTimeout(state.saveTimer);state.saveTimer=setTimeout(saveProject,0)}
async function saveProject(){if(!state.root)return;state.savePromise=state.savePromise.then(async()=>{const d=await state.root.getDirectoryHandle(".LineageAssetStudio",{create:true});await writeJSON(d,"project.json",projectPayload())}).catch(e=>showNotice(`自動儲存失敗：${e.message}`,true));return state.savePromise}

async function importProject(e){const file=e.target.files[0];if(!file)return;try{applyProject(JSON.parse(await file.text()));await saveNameData();changed("專案分類與名稱進度已匯入並儲存。") }catch(err){showNotice(`匯入失敗：${err.message}`,true)}finally{e.target.value=""}}
function exportCSV(){const cols=["uid","sourceType","spriteName","assetPrefix","originalNumber","lang","fileName","relativePath","width","height","category","categoryLabel","categoryPath","nameId","assetName","nameStatus","nameSource","nameConfidence","tags"],q=v=>`"${String(v??"").replaceAll('"','""')}"`,rows=[cols.join(","),...publicAssets().map(a=>({...a,assetName:resolvedName(a)})).map(a=>cols.map(k=>q(k==="tags"?a.tags.join("|"):k==="categoryPath"?a.categoryPath.join("|"):a[k])).join(","))];download("assets_index.csv","\ufeff"+rows.join("\r\n"),"text/csv;charset=utf-8")}
function downloadJSON(name,data){download(name,JSON.stringify(data,null,2),"application/json")}
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}

async function openMediaExport(){
  if(!state.root)return showNotice("請先選擇 LineageAssets 資料夾。",true);
  $("mediaExportDialog").showModal();$("mediaFileList").textContent="正在掃描支援的媒體檔案…";state.mediaFiles=[];state.mediaSelected.clear();
  try{await walkMedia(state.root,"",state.mediaFiles);state.mediaFiles.sort((a,b)=>a.path.localeCompare(b.path,undefined,{numeric:true}));const selectedPaths=new Set(selectedAssets().map(a=>a.relativePath.toLowerCase()));state.mediaFiles.forEach(f=>{if(selectedPaths.has(f.path.toLowerCase()))state.mediaSelected.add(f.path)});$("mediaSearch").value="";renderMediaFiles()}catch(e){$("mediaExportDialog").close();showNotice(`媒體掃描失敗：${e.message}`,true)}
}
async function openSelectedMediaExport(){
  const assets=selectedAssets();if(!assets.length)return showNotice("請先選取要匯出的素材。",true);
  $("mediaExportDialog").showModal();$("mediaFileList").textContent="正在準備已選素材…";state.mediaFiles=[];state.mediaSelected.clear();
  try{for(const asset of assets){const handle=await resolveFile(asset.relativePath),ext=fileExtension(asset.fileName);if(MEDIA_EXTS.has(ext))state.mediaFiles.push({name:asset.fileName,path:asset.relativePath,handle,ext,asset})}state.mediaFiles.sort((a,b)=>a.path.localeCompare(b.path,undefined,{numeric:true}));state.mediaFiles.forEach(f=>state.mediaSelected.add(f.path));$("mediaSearch").value="";renderMediaFiles();$("mediaExportSummary").textContent=`已帶入 ${state.mediaFiles.length.toLocaleString()} 個選取素材`}catch(e){$("mediaExportDialog").close();showNotice(`準備匯出失敗：${e.message}`,true)}
}
async function walkMedia(dir,prefix,out){for await(const [name,h] of dir.entries()){if(name===".LineageAssetStudio")continue;const path=prefix?`${prefix}/${name}`:name;if(h.kind==="directory")await walkMedia(h,path,out);else{const ext=fileExtension(name);if(MEDIA_EXTS.has(ext))out.push({name,path,handle:h,ext})}}}
function mediaFiltered(){const q=$("mediaSearch").value.trim().toLowerCase();return q?state.mediaFiles.filter(f=>f.path.toLowerCase().includes(q)):state.mediaFiles}
function renderMediaFiles(){const files=mediaFiltered(),shown=files.slice(0,600),root=$("mediaFileList");root.replaceChildren(...shown.map(f=>{const row=el("label","media-row"),check=document.createElement("input"),name=el("span","",f.name),path=el("code","",f.path);check.type="checkbox";check.checked=state.mediaSelected.has(f.path);check.onchange=()=>{check.checked?state.mediaSelected.add(f.path):state.mediaSelected.delete(f.path);updateMediaCount()};row.append(check,name,path);return row}));if(!files.length)root.append(el("div","media-row","找不到支援的媒體檔案"));if(files.length>shown.length)root.append(el("div","media-row",`僅顯示前 ${shown.length} 筆；可使用搜尋縮小範圍。`));$("mediaExportSummary").textContent=`資料庫內共 ${state.mediaFiles.length.toLocaleString()} 個支援檔案`;updateMediaCount()}
function updateMediaCount(){$("mediaSelectedCount").textContent=`已選 ${state.mediaSelected.size.toLocaleString()} 個`}
function selectAllMedia(){mediaFiltered().forEach(f=>state.mediaSelected.add(f.path));renderMediaFiles()}
async function exportSelectedMedia(){
  const chosen=state.mediaFiles.filter(f=>state.mediaSelected.has(f.path));if(!chosen.length)return showNotice("請先選擇要匯出的媒體檔案。",true);
  let target;try{target=await showDirectoryPicker({mode:"readwrite",id:"lineage-media-export"})}catch(e){if(e.name!=="AbortError")showNotice(e.message,true);return}
  $("confirmMediaExport").disabled=true;let ok=0,failed=[];
  for(const item of chosen){try{const file=await item.handle.getFile(),actual=await detectMediaType(file);if(!sameMediaType(item.ext,actual))throw Error(`內容是 ${actual?.toUpperCase()||"未知格式"}，與副檔名不符`);const toJpg=item.ext==="png"&&$("pngExportFormat").value==="jpg",ext=toJpg?"jpg":item.ext,asset=item.asset||state.assets.find(a=>a.relativePath===item.path),name=mediaExportName(item,asset,ext),output=toJpg?await pngToJpeg(file):file,dir=$("exportCategoryFolders").checked&&asset?await exportCategoryDirectory(target,asset):target;await writeUniqueFile(dir,name,output);ok++}catch(e){failed.push(`${item.path}：${e.message}`)}}
  $("confirmMediaExport").disabled=false;$("mediaExportDialog").close();showNotice(`匯出完成：${ok} 個成功${failed.length?`，${failed.length} 個失敗（詳見瀏覽器主控台）`:""}。`,failed.length>0);if(failed.length)console.warn("媒體匯出失敗",failed)
}
function safeFilePart(value){return String(value||"").replace(/[<>:"/\\|?*\x00-\x1f]/g,"_").replace(/[. ]+$/g,"").trim()||"unnamed"}
function mediaExportName(item,asset,ext){const format=$("mediaNameFormat").value,label=resolvedName(asset),original=replaceExtension(item.name,ext);if(format==="original"||!label)return original;const base=format==="name_uid"?`${safeFilePart(label)}__${safeFilePart(asset.uid)}`:safeFilePart(label);return`${base}.${ext}`}
async function exportCategoryDirectory(root,asset){let dir=root;for(const part of asset.categoryPath||[]){if(String(part).toLowerCase()==="unknown")continue;dir=await dir.getDirectoryHandle(safeFilePart(part),{create:true})}return dir}
async function chooseMediaImport(){
  if(!state.root)return showNotice("請先選擇 LineageAssets 資料夾。",true);if(!window.showOpenFilePicker)return showNotice("此瀏覽器不支援媒體檔案選擇，請使用 Chrome 或 Edge。",true);
  let handles;try{handles=await showOpenFilePicker({multiple:true,excludeAcceptAllOption:true,types:[{description:"支援的媒體檔案",accept:{"image/png":[".png"],"image/jpeg":[".jpg",".jpeg"],"audio/ogg":[".ogg"],"audio/wav":[".wav"],"audio/mpeg":[".mp3"],"video/mp4":[".mp4"]}}]})}catch(e){if(e.name!=="AbortError")showNotice(e.message,true);return}
  const valid=[],invalid=[];for(const h of handles){const f=await h.getFile(),ext=fileExtension(f.name),actual=await detectMediaType(f);if(MEDIA_EXTS.has(ext)&&sameMediaType(ext,actual))valid.push({handle:h,file:f});else invalid.push(`${f.name}（內容格式：${actual||"無法辨識"}）`)}if(!valid.length)return showNotice(`沒有可匯入的有效媒體檔案。${invalid.length?" 部分檔案內容與副檔名不符。":""}`,true);if(invalid.length)console.warn("已拒絕格式不符的匯入檔案",invalid);
  state.importFiles=valid;state.folderStack=[{handle:state.root,name:state.root.name}];$("importFileSummary").textContent=`準備匯入 ${valid.length} 個檔案${invalid.length?`；已拒絕 ${invalid.length} 個格式不符檔案`:""}`;await renderFolderBrowser();$("mediaImportDialog").showModal()
}
async function renderFolderBrowser(){const current=state.folderStack.at(-1),folders=[];for await(const [name,h] of current.handle.entries())if(h.kind==="directory"&&name!==".LineageAssetStudio")folders.push({name,handle:h});folders.sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true}));$("folderPath").textContent=state.folderStack.map(x=>x.name).join(" / ");$("folderUp").disabled=state.folderStack.length===1;$("folderList").replaceChildren(...folders.map(f=>{const row=el("div","folder-row"),name=el("span","",`📁 ${f.name}`),open=el("button","","開啟");row.append(name,open);row.ondblclick=()=>enterFolder(f);open.onclick=()=>enterFolder(f);return row}),...(folders.length?[]:[el("div","folder-row","此位置沒有子資料夾")]))}
async function enterFolder(folder){state.folderStack.push(folder);await renderFolderBrowser()}
async function folderUp(){if(state.folderStack.length>1){state.folderStack.pop();await renderFolderBrowser()}}
async function createImportFolder(){const name=$("newFolderName").value.trim();if(!name||/[<>:"/\\|?*]/.test(name)||name==="."||name==="..")return showNotice("資料夾名稱無效。",true);try{const h=await state.folderStack.at(-1).handle.getDirectoryHandle(name,{create:true});$("newFolderName").value="";await renderFolderBrowser();showNotice(`已建立資料夾「${name}」。`)}catch(e){showNotice(`建立資料夾失敗：${e.message}`,true)}}
async function importToCurrentFolder(){const target=state.folderStack.at(-1).handle;$("confirmMediaImport").disabled=true;let ok=0,failed=[];for(const item of state.importFiles){try{await writeUniqueFile(target,item.file.name,item.file);ok++}catch(e){failed.push(`${item.file.name}：${e.message}`)}}$("confirmMediaImport").disabled=false;$("mediaImportDialog").close();showNotice(`匯入完成：${ok} 個成功${failed.length?`，${failed.length} 個失敗`:""}。若匯入 PNG 到素材結構，請按「重新掃描」。`,failed.length>0);if(failed.length)console.warn("媒體匯入失敗",failed)}
function fileExtension(name){return(name.split(".").pop()||"").toLowerCase()}
function replaceExtension(name,ext){return name.replace(/\.[^.]+$/,"")+`.`+ext}
function sameMediaType(ext,type){return(ext==="jpg"||ext==="jpeg")?type==="jpg":ext===type}
async function detectMediaType(file){const b=new Uint8Array(await file.slice(0,16).arrayBuffer()),ascii=(s,e)=>String.fromCharCode(...b.slice(s,e));if(b[0]===0x89&&ascii(1,4)==="PNG")return"png";if(b[0]===0xff&&b[1]===0xd8&&b[2]===0xff)return"jpg";if(ascii(0,4)==="OggS")return"ogg";if(ascii(0,4)==="RIFF"&&ascii(8,12)==="WAVE")return"wav";if(ascii(0,3)==="ID3"||(b[0]===0xff&&(b[1]&0xe0)===0xe0))return"mp3";if(ascii(4,8)==="ftyp")return"mp4";return null}
async function pngToJpeg(file){const image=await createImageBitmap(file),canvas=document.createElement("canvas");canvas.width=image.width;canvas.height=image.height;const ctx=canvas.getContext("2d");ctx.fillStyle="#ffffff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0);image.close();return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error("JPG 轉換失敗")),"image/jpeg",0.92))}
async function writeUniqueFile(dir,requestedName,data){const dot=requestedName.lastIndexOf("."),base=dot>0?requestedName.slice(0,dot):requestedName,ext=dot>0?requestedName.slice(dot):"";let name=requestedName,n=1;while(await fileExists(dir,name))name=`${base} (${n++})${ext}`;const h=await dir.getFileHandle(name,{create:true}),w=await h.createWritable();await w.write(data);await w.close();return name}
async function fileExists(dir,name){try{await dir.getFileHandle(name);return true}catch(e){if(e.name==="NotFoundError")return false;throw e}}

async function initializeBackupSystem(){if(!state.root)return;try{const studio=await state.root.getDirectoryHandle(".LineageAssetStudio",{create:true});await studio.getDirectoryHandle("backups",{create:true});await loadNameData(studio);$("createBackup").disabled=false;$("viewBackups").disabled=false;await refreshBackupStats()}catch(e){showNotice(`專案資料初始化失敗：${e.message}`,true)}}
function backupTimestamp(date=new Date()){const p=n=>String(n).padStart(2,"0");return`${date.getFullYear()}-${p(date.getMonth()+1)}-${p(date.getDate())}_${p(date.getHours())}-${p(date.getMinutes())}-${p(date.getSeconds())}`}
async function backupDirectory(){const studio=await state.root.getDirectoryHandle(".LineageAssetStudio",{create:true});return studio.getDirectoryHandle("backups",{create:true})}
async function listBackupFiles(){const dir=await backupDirectory(),items=[];for await(const [name,h]of dir.entries()){if(h.kind==="file"&&name.toLowerCase().endsWith(".json")){const file=await h.getFile();items.push({name,handle:h,size:file.size,lastModified:file.lastModified,file})}}return items.sort((a,b)=>b.lastModified-a.lastModified)}
async function refreshBackupStats(){const all=await listBackupFiles(),snapshots=all.filter(x=>/^project_\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}\.json$/.test(x.name));state.backupCount=snapshots.length;if(snapshots.length){const latest=new Date(snapshots[0].lastModified);if(!state.lastBackupAt||latest>state.lastBackupAt)state.lastBackupAt=latest}updateBackupStatus();return all}
function updateBackupStatus(){const label=state.lastBackupAt?state.lastBackupAt.toLocaleString():"尚無";$("backupStatus").textContent=state.lastBackupAt?`最近備份 ${label}｜共 ${state.backupCount} 份`:`尚無備份｜共 ${state.backupCount} 份`;if($("statusBackup"))$("statusBackup").textContent=label}
async function uniqueBackupName(dir,prefix="project"){const now=Date.now();for(let i=0;i<120;i++){const name=`${prefix}_${backupTimestamp(new Date(now+i*1000))}.json`;if(!await fileExists(dir,name))return name}throw Error("無法建立唯一備份檔名")}
async function createSnapshot(reason="auto"){
  if(!state.root||state.backupBusy)return;state.backupBusy=true;$("createBackup").disabled=true;
  const oldCount=state.classificationsSinceBackup,oldTime=state.lastBackupAt,oldDirty=state.projectDirty,oldSince=state.dirtySince;
  try{await saveProject();const dir=await backupDirectory(),name=await uniqueBackupName(dir,"project");state.classificationsSinceBackup=0;state.lastBackupAt=new Date();state.projectDirty=false;state.dirtySince=null;await writeJSON(dir,name,{...projectPayload(),snapshot:{reason,createdAt:state.lastBackupAt.toISOString()}});await enforceBackupRetention(dir);await saveProject();await refreshBackupStats();showNotice(`已建立備份：${name}`)}catch(e){state.classificationsSinceBackup=oldCount;state.lastBackupAt=oldTime;state.projectDirty=oldDirty;state.dirtySince=oldSince;showNotice(`建立備份失敗：${e.message}`,true)}finally{state.backupBusy=false;$("createBackup").disabled=false}
}
async function enforceBackupRetention(dir){const files=[];for await(const [name,h]of dir.entries())if(h.kind==="file"&&/^project_\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}\.json$/.test(name)){const f=await h.getFile();files.push({name,time:f.lastModified})}files.sort((a,b)=>b.time-a.time);for(const old of files.slice(20))await dir.removeEntry(old.name)}
async function checkTimedBackup(){if(!state.root||!state.projectDirty||!state.dirtySince||state.backupBusy)return;if(Date.now()-state.dirtySince.getTime()>=30*60*1000)await createSnapshot("30 分鐘自動備份")}
async function openBackupDialog(){$("backupDialog").showModal();$("backupList").textContent="正在讀取備份…";try{const files=await refreshBackupStats();$("backupDialogSummary").textContent=`共 ${files.length} 個備份檔；自動快照最多保留 20 份`;$("backupList").replaceChildren(...files.map(item=>{const row=el("div","backup-row"),name=el("span","",item.name),time=document.createElement("time"),size=el("small","",formatBytes(item.size)),restore=el("button","","還原此備份");time.textContent=new Date(item.lastModified).toLocaleString();restore.onclick=()=>restoreBackup(item);row.append(name,time,size,restore);return row}),...(files.length?[]:[el("div","backup-row","目前沒有備份")]))}catch(e){$("backupList").textContent=`讀取失敗：${e.message}`}}
function formatBytes(bytes){if(bytes<1024)return`${bytes} B`;if(bytes<1048576)return`${(bytes/1024).toFixed(1)} KB`;return`${(bytes/1048576).toFixed(1)} MB`}
async function restoreBackup(item){if(!confirm(`確定還原 ${item.name}？\n目前 project.json 會先建立 emergency backup。`))return;const restoreButtons=$("backupList").querySelectorAll("button");restoreButtons.forEach(b=>b.disabled=true);try{const data=JSON.parse(await item.file.text());if(!data||typeof data.assets!=="object")throw Error("備份格式不正確");await saveProject();const studio=await state.root.getDirectoryHandle(".LineageAssetStudio",{create:true}),dir=await studio.getDirectoryHandle("backups",{create:true}),emergency=await uniqueBackupName(dir,"emergency_backup");await writeJSON(dir,emergency,projectPayload());await writeJSON(studio,"project.json",data);state.assets=normalizeAssets(await readJSON(studio,"assets_index.json"));applyProject(data);state.classificationsSinceBackup=Number(data.backupState?.classificationsSinceBackup)||0;state.lastBackupAt=data.backupState?.lastBackupAt?new Date(data.backupState.lastBackupAt):state.lastBackupAt;state.projectDirty=false;state.dirtySince=null;state.selected.clear();state.undo=[];state.redo=[];CATEGORIES=categoryTreeValues();buildCategoryTree();refreshCategoryControls();await writeJSON(studio,"settings.json",settingsPayload());afterLoad();await refreshBackupStats();$("backupDialog").close();showNotice(`已還原 ${item.name}；還原前資料已保存為 ${emergency}。`)}catch(e){showNotice(`還原備份失敗：${e.message}`,true);restoreButtons.forEach(b=>b.disabled=false)}}

function reportLines(){return state.scanWarnings.length?state.scanWarnings:["沒有無法讀取的檔案或資料夾。"]}
function openReport(){$("reportSearch").value="";renderReport();$("reportDialog").showModal()}
function renderReport(){const q=$("reportSearch").value.trim().toLowerCase(),all=reportLines(),shown=q?all.filter(x=>x.toLowerCase().includes(q)):all;$("reportSummary").textContent=`掃描時間：${state.lastScanAt?.toLocaleString()||"尚未掃描"}｜警告 ${state.scanWarnings.length.toLocaleString()} 筆${q?`｜符合 ${shown.length.toLocaleString()} 筆`:""}`;$("reportContent").textContent=shown.join("\n")}
async function copyReport(){try{await navigator.clipboard.writeText(reportText());$("copyReport").textContent="已複製";setTimeout(()=>$("copyReport").textContent="複製報告",1500)}catch{showNotice("無法使用剪貼簿，請改用下載報告。",true)}}
function downloadReport(){download("lineage_asset_scan_report.txt","\ufeff"+reportText(),"text/plain;charset=utf-8")}
function reportText(){return["Lineage Asset Studio 掃描報告",`時間：${state.lastScanAt?.toLocaleString()||"尚未掃描"}`,`警告數：${state.scanWarnings.length}`,"",...reportLines()].join("\r\n")}

function fillSelect(select,items,numeric=false){const first=select.options[0]?.value===""?select.options[0].cloneNode(true):null;select.replaceChildren(...(first?[first]:[]),...items.sort(numeric?(a,b)=>a.localeCompare(b,undefined,{numeric:true}):undefined).map(v=>new Option(v,v)))}
function uniq(a,numeric=false){return [...new Set(a)].sort(numeric?(x,y)=>x.localeCompare(y,undefined,{numeric:true}):undefined)}
function el(tag,cls="",text=""){const e=document.createElement(tag);e.className=cls;if(text!=="")e.textContent=text;return e}
function showNotice(text,error=false){const n=$("notice");n.textContent=text;n.className="notice"+(error?" error":"");clearTimeout(showNotice.timer);if(!error)showNotice.timer=setTimeout(()=>n.classList.add("hidden"),6000)}
function setBusy(on,text="",ratio=0){$("progress").classList.toggle("hidden",!on);$("progress").querySelector("div").style.width=`${Math.round(ratio*100)}%`;$("progress").querySelector("span").textContent=text;$("chooseFolder").disabled=on;$("rescan").disabled=on||!state.root}
const nextFrame=()=>new Promise(r=>requestAnimationFrame(r));
function db(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbGet(k){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbPut(k,v){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(STORE,"readwrite").objectStore(STORE).put(v,k);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
